// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: api.proto

package teeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error response structure
type ApiError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // Error code (e.g., "ERROR_INVALID_CLAIM")
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Human-readable error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiError) Reset() {
	*x = ApiError{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiError) ProtoMessage() {}

func (x *ApiError) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiError.ProtoReflect.Descriptor instead.
func (*ApiError) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *ApiError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApiError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Claim request data structure
type ClaimRequestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                        // Provider name (e.g., "http", "github")
	Parameters    string                 `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`                    // Provider parameters as JSON string
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`                              // ETH address of claim owner
	TimestampS    int64                  `protobuf:"varint,4,opt,name=timestamp_s,json=timestampS,proto3" json:"timestamp_s,omitempty"` // Unix timestamp in seconds
	Context       string                 `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`                          // Optional context as JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRequestData) Reset() {
	*x = ClaimRequestData{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequestData) ProtoMessage() {}

func (x *ClaimRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequestData.ProtoReflect.Descriptor instead.
func (*ClaimRequestData) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimRequestData) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ClaimRequestData) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

func (x *ClaimRequestData) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ClaimRequestData) GetTimestampS() int64 {
	if x != nil {
		return x.TimestampS
	}
	return 0
}

func (x *ClaimRequestData) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

// Request signatures
type ClaimTeeBundleRequest_Signatures struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestSignature []byte                 `protobuf:"bytes,1,opt,name=request_signature,json=requestSignature,proto3" json:"request_signature,omitempty"` // Signature over serialized ClaimTeeBundleRequest (without signatures field)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClaimTeeBundleRequest_Signatures) Reset() {
	*x = ClaimTeeBundleRequest_Signatures{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTeeBundleRequest_Signatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTeeBundleRequest_Signatures) ProtoMessage() {}

func (x *ClaimTeeBundleRequest_Signatures) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTeeBundleRequest_Signatures.ProtoReflect.Descriptor instead.
func (*ClaimTeeBundleRequest_Signatures) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimTeeBundleRequest_Signatures) GetRequestSignature() []byte {
	if x != nil {
		return x.RequestSignature
	}
	return nil
}

// Main request message for TEE bundle claim
type ClaimTeeBundleRequest struct {
	state              protoimpl.MessageState            `protogen:"open.v1"`
	VerificationBundle []byte                            `protobuf:"bytes,1,opt,name=verification_bundle,json=verificationBundle,proto3" json:"verification_bundle,omitempty"` // Serialized VerificationBundlePB
	Data               *ClaimRequestData                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                                       // Claim request data
	Signatures         *ClaimTeeBundleRequest_Signatures `protobuf:"bytes,3,opt,name=signatures,proto3" json:"signatures,omitempty"`                                           // Request signatures
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClaimTeeBundleRequest) Reset() {
	*x = ClaimTeeBundleRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTeeBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTeeBundleRequest) ProtoMessage() {}

func (x *ClaimTeeBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTeeBundleRequest.ProtoReflect.Descriptor instead.
func (*ClaimTeeBundleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimTeeBundleRequest) GetVerificationBundle() []byte {
	if x != nil {
		return x.VerificationBundle
	}
	return nil
}

func (x *ClaimTeeBundleRequest) GetData() *ClaimRequestData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClaimTeeBundleRequest) GetSignatures() *ClaimTeeBundleRequest_Signatures {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// Provider claim data (the validated claim result)
type ProviderClaimData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                    // Unique claim identifier
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`                        // Provider name
	Parameters    string                 `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`                    // Provider parameters as JSON string
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`                              // ETH address of claim owner
	TimestampS    int64                  `protobuf:"varint,5,opt,name=timestamp_s,json=timestampS,proto3" json:"timestamp_s,omitempty"` // Unix timestamp in seconds
	Context       string                 `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`                          // Context as JSON string
	Epoch         string                 `protobuf:"bytes,7,opt,name=epoch,proto3" json:"epoch,omitempty"`                              // Claim epoch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderClaimData) Reset() {
	*x = ProviderClaimData{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderClaimData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderClaimData) ProtoMessage() {}

func (x *ProviderClaimData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderClaimData.ProtoReflect.Descriptor instead.
func (*ProviderClaimData) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderClaimData) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ProviderClaimData) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProviderClaimData) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

func (x *ProviderClaimData) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ProviderClaimData) GetTimestampS() int64 {
	if x != nil {
		return x.TimestampS
	}
	return 0
}

func (x *ProviderClaimData) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ProviderClaimData) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

// Response signatures from attestor
type ClaimTeeBundleResponse_Signatures struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClaimSignature  []byte                 `protobuf:"bytes,1,opt,name=claim_signature,json=claimSignature,proto3" json:"claim_signature,omitempty"`    // Signature over ProviderClaimData
	ResultSignature []byte                 `protobuf:"bytes,2,opt,name=result_signature,json=resultSignature,proto3" json:"result_signature,omitempty"` // Signature over complete response
	AttestorAddress string                 `protobuf:"bytes,3,opt,name=attestor_address,json=attestorAddress,proto3" json:"attestor_address,omitempty"` // ETH address of attestor that signed
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClaimTeeBundleResponse_Signatures) Reset() {
	*x = ClaimTeeBundleResponse_Signatures{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTeeBundleResponse_Signatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTeeBundleResponse_Signatures) ProtoMessage() {}

func (x *ClaimTeeBundleResponse_Signatures) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTeeBundleResponse_Signatures.ProtoReflect.Descriptor instead.
func (*ClaimTeeBundleResponse_Signatures) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimTeeBundleResponse_Signatures) GetClaimSignature() []byte {
	if x != nil {
		return x.ClaimSignature
	}
	return nil
}

func (x *ClaimTeeBundleResponse_Signatures) GetResultSignature() []byte {
	if x != nil {
		return x.ResultSignature
	}
	return nil
}

func (x *ClaimTeeBundleResponse_Signatures) GetAttestorAddress() string {
	if x != nil {
		return x.AttestorAddress
	}
	return ""
}

// Response message for TEE bundle claim
type ClaimTeeBundleResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Claim         *ProviderClaimData                 `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`           // The validated claim (on success)
	Error         *ApiError                          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`           // Error details (on failure)
	Signatures    *ClaimTeeBundleResponse_Signatures `protobuf:"bytes,3,opt,name=signatures,proto3" json:"signatures,omitempty"` // Attestor signatures
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTeeBundleResponse) Reset() {
	*x = ClaimTeeBundleResponse{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTeeBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTeeBundleResponse) ProtoMessage() {}

func (x *ClaimTeeBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTeeBundleResponse.ProtoReflect.Descriptor instead.
func (*ClaimTeeBundleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimTeeBundleResponse) GetClaim() *ProviderClaimData {
	if x != nil {
		return x.Claim
	}
	return nil
}

func (x *ClaimTeeBundleResponse) GetError() *ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ClaimTeeBundleResponse) GetSignatures() *ClaimTeeBundleResponse_Signatures {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// RPC message envelope for WebSocket communication
type RPCMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*RPCMessage_ClaimTeeBundleRequest
	//	*RPCMessage_ClaimTeeBundleResponse
	Type          isRPCMessage_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCMessage) Reset() {
	*x = RPCMessage{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCMessage) ProtoMessage() {}

func (x *RPCMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCMessage.ProtoReflect.Descriptor instead.
func (*RPCMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *RPCMessage) GetType() isRPCMessage_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *RPCMessage) GetClaimTeeBundleRequest() *ClaimTeeBundleRequest {
	if x != nil {
		if x, ok := x.Type.(*RPCMessage_ClaimTeeBundleRequest); ok {
			return x.ClaimTeeBundleRequest
		}
	}
	return nil
}

func (x *RPCMessage) GetClaimTeeBundleResponse() *ClaimTeeBundleResponse {
	if x != nil {
		if x, ok := x.Type.(*RPCMessage_ClaimTeeBundleResponse); ok {
			return x.ClaimTeeBundleResponse
		}
	}
	return nil
}

type isRPCMessage_Type interface {
	isRPCMessage_Type()
}

type RPCMessage_ClaimTeeBundleRequest struct {
	ClaimTeeBundleRequest *ClaimTeeBundleRequest `protobuf:"bytes,1,opt,name=claim_tee_bundle_request,json=claimTeeBundleRequest,proto3,oneof"`
}

type RPCMessage_ClaimTeeBundleResponse struct {
	ClaimTeeBundleResponse *ClaimTeeBundleResponse `protobuf:"bytes,2,opt,name=claim_tee_bundle_response,json=claimTeeBundleResponse,proto3,oneof"`
}

func (*RPCMessage_ClaimTeeBundleRequest) isRPCMessage_Type() {}

func (*RPCMessage_ClaimTeeBundleResponse) isRPCMessage_Type() {}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\bteeproto\"8\n" +
	"\bApiError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9f\x01\n" +
	"\x10ClaimRequestData\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x01(\tR\n" +
	"parameters\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x1f\n" +
	"\vtimestamp_s\x18\x04 \x01(\x03R\n" +
	"timestampS\x12\x18\n" +
	"\acontext\x18\x05 \x01(\tR\acontext\"O\n" +
	" ClaimTeeBundleRequest_Signatures\x12+\n" +
	"\x11request_signature\x18\x01 \x01(\fR\x10requestSignature\"\xc4\x01\n" +
	"\x15ClaimTeeBundleRequest\x12/\n" +
	"\x13verification_bundle\x18\x01 \x01(\fR\x12verificationBundle\x12.\n" +
	"\x04data\x18\x02 \x01(\v2\x1a.teeproto.ClaimRequestDataR\x04data\x12J\n" +
	"\n" +
	"signatures\x18\x03 \x01(\v2*.teeproto.ClaimTeeBundleRequest_SignaturesR\n" +
	"signatures\"\xd6\x01\n" +
	"\x11ProviderClaimData\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tR\n" +
	"parameters\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x1f\n" +
	"\vtimestamp_s\x18\x05 \x01(\x03R\n" +
	"timestampS\x12\x18\n" +
	"\acontext\x18\x06 \x01(\tR\acontext\x12\x14\n" +
	"\x05epoch\x18\a \x01(\tR\x05epoch\"\xa2\x01\n" +
	"!ClaimTeeBundleResponse_Signatures\x12'\n" +
	"\x0fclaim_signature\x18\x01 \x01(\fR\x0eclaimSignature\x12)\n" +
	"\x10result_signature\x18\x02 \x01(\fR\x0fresultSignature\x12)\n" +
	"\x10attestor_address\x18\x03 \x01(\tR\x0fattestorAddress\"\xc2\x01\n" +
	"\x16ClaimTeeBundleResponse\x121\n" +
	"\x05claim\x18\x01 \x01(\v2\x1b.teeproto.ProviderClaimDataR\x05claim\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\x12.teeproto.ApiErrorR\x05error\x12K\n" +
	"\n" +
	"signatures\x18\x03 \x01(\v2+.teeproto.ClaimTeeBundleResponse_SignaturesR\n" +
	"signatures\"\xcf\x01\n" +
	"\n" +
	"RPCMessage\x12Z\n" +
	"\x18claim_tee_bundle_request\x18\x01 \x01(\v2\x1f.teeproto.ClaimTeeBundleRequestH\x00R\x15claimTeeBundleRequest\x12]\n" +
	"\x19claim_tee_bundle_response\x18\x02 \x01(\v2 .teeproto.ClaimTeeBundleResponseH\x00R\x16claimTeeBundleResponseB\x06\n" +
	"\x04typeB\x18Z\x16tee-mpc/proto;teeprotob\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_goTypes = []any{
	(*ApiError)(nil),                          // 0: teeproto.ApiError
	(*ClaimRequestData)(nil),                  // 1: teeproto.ClaimRequestData
	(*ClaimTeeBundleRequest_Signatures)(nil),  // 2: teeproto.ClaimTeeBundleRequest_Signatures
	(*ClaimTeeBundleRequest)(nil),             // 3: teeproto.ClaimTeeBundleRequest
	(*ProviderClaimData)(nil),                 // 4: teeproto.ProviderClaimData
	(*ClaimTeeBundleResponse_Signatures)(nil), // 5: teeproto.ClaimTeeBundleResponse_Signatures
	(*ClaimTeeBundleResponse)(nil),            // 6: teeproto.ClaimTeeBundleResponse
	(*RPCMessage)(nil),                        // 7: teeproto.RPCMessage
}
var file_api_proto_depIdxs = []int32{
	1, // 0: teeproto.ClaimTeeBundleRequest.data:type_name -> teeproto.ClaimRequestData
	2, // 1: teeproto.ClaimTeeBundleRequest.signatures:type_name -> teeproto.ClaimTeeBundleRequest_Signatures
	4, // 2: teeproto.ClaimTeeBundleResponse.claim:type_name -> teeproto.ProviderClaimData
	0, // 3: teeproto.ClaimTeeBundleResponse.error:type_name -> teeproto.ApiError
	5, // 4: teeproto.ClaimTeeBundleResponse.signatures:type_name -> teeproto.ClaimTeeBundleResponse_Signatures
	3, // 5: teeproto.RPCMessage.claim_tee_bundle_request:type_name -> teeproto.ClaimTeeBundleRequest
	6, // 6: teeproto.RPCMessage.claim_tee_bundle_response:type_name -> teeproto.ClaimTeeBundleResponse
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[7].OneofWrappers = []any{
		(*RPCMessage_ClaimTeeBundleRequest)(nil),
		(*RPCMessage_ClaimTeeBundleResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
