// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: bundle.proto

package teeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OPRF verification data for a single hashed range
type OPRFVerificationData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StreamPos         uint32                 `protobuf:"varint,1,opt,name=stream_pos,json=streamPos,proto3" json:"stream_pos,omitempty"`                          // Position in the consolidated TLS stream
	StreamLength      uint32                 `protobuf:"varint,2,opt,name=stream_length,json=streamLength,proto3" json:"stream_length,omitempty"`                 // Length of data in the stream
	PublicSignalsJson []byte                 `protobuf:"bytes,3,opt,name=public_signals_json,json=publicSignalsJson,proto3" json:"public_signals_json,omitempty"` // ZK proof and public parameters (InputVerifyParams)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OPRFVerificationData) Reset() {
	*x = OPRFVerificationData{}
	mi := &file_bundle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OPRFVerificationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OPRFVerificationData) ProtoMessage() {}

func (x *OPRFVerificationData) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OPRFVerificationData.ProtoReflect.Descriptor instead.
func (*OPRFVerificationData) Descriptor() ([]byte, []int) {
	return file_bundle_proto_rawDescGZIP(), []int{0}
}

func (x *OPRFVerificationData) GetStreamPos() uint32 {
	if x != nil {
		return x.StreamPos
	}
	return 0
}

func (x *OPRFVerificationData) GetStreamLength() uint32 {
	if x != nil {
		return x.StreamLength
	}
	return 0
}

func (x *OPRFVerificationData) GetPublicSignalsJson() []byte {
	if x != nil {
		return x.PublicSignalsJson
	}
	return nil
}

// Single artefact produced by client for offline verification
type VerificationBundle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed transcripts
	TeekSigned *SignedMessage `protobuf:"bytes,1,opt,name=teek_signed,json=teekSigned,proto3" json:"teek_signed,omitempty"` // BODY_TYPE_K_OUTPUT (contains signed certificate_info)
	TeetSigned *SignedMessage `protobuf:"bytes,2,opt,name=teet_signed,json=teetSigned,proto3" json:"teet_signed,omitempty"` // BODY_TYPE_T_OUTPUT
	// OPRF verification data for hashed ranges
	OprfVerifications []*OPRFVerificationData `protobuf:"bytes,3,rep,name=oprf_verifications,json=oprfVerifications,proto3" json:"oprf_verifications,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerificationBundle) Reset() {
	*x = VerificationBundle{}
	mi := &file_bundle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationBundle) ProtoMessage() {}

func (x *VerificationBundle) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationBundle.ProtoReflect.Descriptor instead.
func (*VerificationBundle) Descriptor() ([]byte, []int) {
	return file_bundle_proto_rawDescGZIP(), []int{1}
}

func (x *VerificationBundle) GetTeekSigned() *SignedMessage {
	if x != nil {
		return x.TeekSigned
	}
	return nil
}

func (x *VerificationBundle) GetTeetSigned() *SignedMessage {
	if x != nil {
		return x.TeetSigned
	}
	return nil
}

func (x *VerificationBundle) GetOprfVerifications() []*OPRFVerificationData {
	if x != nil {
		return x.OprfVerifications
	}
	return nil
}

var File_bundle_proto protoreflect.FileDescriptor

const file_bundle_proto_rawDesc = "" +
	"\n" +
	"\fbundle.proto\x12\bteeproto\x1a\rsigning.proto\"\x8a\x01\n" +
	"\x14OPRFVerificationData\x12\x1d\n" +
	"\n" +
	"stream_pos\x18\x01 \x01(\rR\tstreamPos\x12#\n" +
	"\rstream_length\x18\x02 \x01(\rR\fstreamLength\x12.\n" +
	"\x13public_signals_json\x18\x03 \x01(\fR\x11publicSignalsJson\"\xd7\x01\n" +
	"\x12VerificationBundle\x128\n" +
	"\vteek_signed\x18\x01 \x01(\v2\x17.teeproto.SignedMessageR\n" +
	"teekSigned\x128\n" +
	"\vteet_signed\x18\x02 \x01(\v2\x17.teeproto.SignedMessageR\n" +
	"teetSigned\x12M\n" +
	"\x12oprf_verifications\x18\x03 \x03(\v2\x1e.teeproto.OPRFVerificationDataR\x11oprfVerificationsB\x18Z\x16tee-mpc/proto;teeprotob\x06proto3"

var (
	file_bundle_proto_rawDescOnce sync.Once
	file_bundle_proto_rawDescData []byte
)

func file_bundle_proto_rawDescGZIP() []byte {
	file_bundle_proto_rawDescOnce.Do(func() {
		file_bundle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bundle_proto_rawDesc), len(file_bundle_proto_rawDesc)))
	})
	return file_bundle_proto_rawDescData
}

var file_bundle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bundle_proto_goTypes = []any{
	(*OPRFVerificationData)(nil), // 0: teeproto.OPRFVerificationData
	(*VerificationBundle)(nil),   // 1: teeproto.VerificationBundle
	(*SignedMessage)(nil),        // 2: teeproto.SignedMessage
}
var file_bundle_proto_depIdxs = []int32{
	2, // 0: teeproto.VerificationBundle.teek_signed:type_name -> teeproto.SignedMessage
	2, // 1: teeproto.VerificationBundle.teet_signed:type_name -> teeproto.SignedMessage
	0, // 2: teeproto.VerificationBundle.oprf_verifications:type_name -> teeproto.OPRFVerificationData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bundle_proto_init() }
func file_bundle_proto_init() {
	if File_bundle_proto != nil {
		return
	}
	file_signing_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bundle_proto_rawDesc), len(file_bundle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bundle_proto_goTypes,
		DependencyIndexes: file_bundle_proto_depIdxs,
		MessageInfos:      file_bundle_proto_msgTypes,
	}.Build()
	File_bundle_proto = out.File
	file_bundle_proto_goTypes = nil
	file_bundle_proto_depIdxs = nil
}
