// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: bundle.proto

package teeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Handshake secrets disclosed for verification/display
type HandshakeSecrets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandshakeKey  []byte                 `protobuf:"bytes,1,opt,name=handshake_key,json=handshakeKey,proto3" json:"handshake_key,omitempty"`
	HandshakeIv   []byte                 `protobuf:"bytes,2,opt,name=handshake_iv,json=handshakeIv,proto3" json:"handshake_iv,omitempty"`
	CipherSuite   uint32                 `protobuf:"varint,3,opt,name=cipher_suite,json=cipherSuite,proto3" json:"cipher_suite,omitempty"` // uint16 fits here
	Algorithm     string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeSecrets) Reset() {
	*x = HandshakeSecrets{}
	mi := &file_bundle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeSecrets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeSecrets) ProtoMessage() {}

func (x *HandshakeSecrets) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeSecrets.ProtoReflect.Descriptor instead.
func (*HandshakeSecrets) Descriptor() ([]byte, []int) {
	return file_bundle_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeSecrets) GetHandshakeKey() []byte {
	if x != nil {
		return x.HandshakeKey
	}
	return nil
}

func (x *HandshakeSecrets) GetHandshakeIv() []byte {
	if x != nil {
		return x.HandshakeIv
	}
	return nil
}

func (x *HandshakeSecrets) GetCipherSuite() uint32 {
	if x != nil {
		return x.CipherSuite
	}
	return 0
}

func (x *HandshakeSecrets) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

// Commitment opening for proof stream
type Opening struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProofStream   []byte                 `protobuf:"bytes,1,opt,name=proof_stream,json=proofStream,proto3" json:"proof_stream,omitempty"` // Str_SP
	ProofKey      []byte                 `protobuf:"bytes,2,opt,name=proof_key,json=proofKey,proto3" json:"proof_key,omitempty"`          // K_SP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Opening) Reset() {
	*x = Opening{}
	mi := &file_bundle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Opening) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opening) ProtoMessage() {}

func (x *Opening) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opening.ProtoReflect.Descriptor instead.
func (*Opening) Descriptor() ([]byte, []int) {
	return file_bundle_proto_rawDescGZIP(), []int{1}
}

func (x *Opening) GetProofStream() []byte {
	if x != nil {
		return x.ProofStream
	}
	return nil
}

func (x *Opening) GetProofKey() []byte {
	if x != nil {
		return x.ProofKey
	}
	return nil
}

// Single artefact produced by client for offline verification
type VerificationBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandshakeKeys *HandshakeSecrets      `protobuf:"bytes,1,opt,name=handshake_keys,json=handshakeKeys,proto3" json:"handshake_keys,omitempty"` // optional
	// Signed transcripts
	TeekSigned *SignedMessage `protobuf:"bytes,2,opt,name=teek_signed,json=teekSigned,proto3" json:"teek_signed,omitempty"` // BODY_TYPE_K_OUTPUT
	TeetSigned *SignedMessage `protobuf:"bytes,3,opt,name=teet_signed,json=teetSigned,proto3" json:"teet_signed,omitempty"` // BODY_TYPE_T_OUTPUT
	// Commitment opening for proof ranges
	Opening       *Opening `protobuf:"bytes,4,opt,name=opening,proto3" json:"opening,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationBundle) Reset() {
	*x = VerificationBundle{}
	mi := &file_bundle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationBundle) ProtoMessage() {}

func (x *VerificationBundle) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationBundle.ProtoReflect.Descriptor instead.
func (*VerificationBundle) Descriptor() ([]byte, []int) {
	return file_bundle_proto_rawDescGZIP(), []int{2}
}

func (x *VerificationBundle) GetHandshakeKeys() *HandshakeSecrets {
	if x != nil {
		return x.HandshakeKeys
	}
	return nil
}

func (x *VerificationBundle) GetTeekSigned() *SignedMessage {
	if x != nil {
		return x.TeekSigned
	}
	return nil
}

func (x *VerificationBundle) GetTeetSigned() *SignedMessage {
	if x != nil {
		return x.TeetSigned
	}
	return nil
}

func (x *VerificationBundle) GetOpening() *Opening {
	if x != nil {
		return x.Opening
	}
	return nil
}

var File_bundle_proto protoreflect.FileDescriptor

const file_bundle_proto_rawDesc = "" +
	"\n" +
	"\fbundle.proto\x12\bteeproto\x1a\rsigning.proto\"\x9b\x01\n" +
	"\x10HandshakeSecrets\x12#\n" +
	"\rhandshake_key\x18\x01 \x01(\fR\fhandshakeKey\x12!\n" +
	"\fhandshake_iv\x18\x02 \x01(\fR\vhandshakeIv\x12!\n" +
	"\fcipher_suite\x18\x03 \x01(\rR\vcipherSuite\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\"I\n" +
	"\aOpening\x12!\n" +
	"\fproof_stream\x18\x01 \x01(\fR\vproofStream\x12\x1b\n" +
	"\tproof_key\x18\x02 \x01(\fR\bproofKey\"\xf8\x01\n" +
	"\x12VerificationBundle\x12A\n" +
	"\x0ehandshake_keys\x18\x01 \x01(\v2\x1a.teeproto.HandshakeSecretsR\rhandshakeKeys\x128\n" +
	"\vteek_signed\x18\x02 \x01(\v2\x17.teeproto.SignedMessageR\n" +
	"teekSigned\x128\n" +
	"\vteet_signed\x18\x03 \x01(\v2\x17.teeproto.SignedMessageR\n" +
	"teetSigned\x12+\n" +
	"\aopening\x18\x04 \x01(\v2\x11.teeproto.OpeningR\aopeningB\x18Z\x16tee-mpc/proto;teeprotob\x06proto3"

var (
	file_bundle_proto_rawDescOnce sync.Once
	file_bundle_proto_rawDescData []byte
)

func file_bundle_proto_rawDescGZIP() []byte {
	file_bundle_proto_rawDescOnce.Do(func() {
		file_bundle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bundle_proto_rawDesc), len(file_bundle_proto_rawDesc)))
	})
	return file_bundle_proto_rawDescData
}

var file_bundle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bundle_proto_goTypes = []any{
	(*HandshakeSecrets)(nil),   // 0: teeproto.HandshakeSecrets
	(*Opening)(nil),            // 1: teeproto.Opening
	(*VerificationBundle)(nil), // 2: teeproto.VerificationBundle
	(*SignedMessage)(nil),      // 3: teeproto.SignedMessage
}
var file_bundle_proto_depIdxs = []int32{
	0, // 0: teeproto.VerificationBundle.handshake_keys:type_name -> teeproto.HandshakeSecrets
	3, // 1: teeproto.VerificationBundle.teek_signed:type_name -> teeproto.SignedMessage
	3, // 2: teeproto.VerificationBundle.teet_signed:type_name -> teeproto.SignedMessage
	1, // 3: teeproto.VerificationBundle.opening:type_name -> teeproto.Opening
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bundle_proto_init() }
func file_bundle_proto_init() {
	if File_bundle_proto != nil {
		return
	}
	file_signing_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bundle_proto_rawDesc), len(file_bundle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bundle_proto_goTypes,
		DependencyIndexes: file_bundle_proto_depIdxs,
		MessageInfos:      file_bundle_proto_msgTypes,
	}.Build()
	File_bundle_proto = out.File
	file_bundle_proto_goTypes = nil
	file_bundle_proto_depIdxs = nil
}
