// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: common.proto

package teeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shared range types
type RequestRedactionRange struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Start  int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Length int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	// Values: "sensitive" or "sensitive_proof"
	Type           string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	RedactionBytes []byte `protobuf:"bytes,4,opt,name=redaction_bytes,json=redactionBytes,proto3" json:"redaction_bytes,omitempty"` // Optional
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestRedactionRange) Reset() {
	*x = RequestRedactionRange{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRedactionRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRedactionRange) ProtoMessage() {}

func (x *RequestRedactionRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRedactionRange.ProtoReflect.Descriptor instead.
func (*RequestRedactionRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *RequestRedactionRange) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *RequestRedactionRange) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *RequestRedactionRange) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RequestRedactionRange) GetRedactionBytes() []byte {
	if x != nil {
		return x.RedactionBytes
	}
	return nil
}

type ResponseRedactionRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseRedactionRange) Reset() {
	*x = ResponseRedactionRange{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseRedactionRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRedactionRange) ProtoMessage() {}

func (x *ResponseRedactionRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRedactionRange.ProtoReflect.Descriptor instead.
func (*ResponseRedactionRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseRedactionRange) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ResponseRedactionRange) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

// Streams and small shared structures
type ResponseDecryptionStreamData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DecryptionStream []byte                 `protobuf:"bytes,1,opt,name=decryption_stream,json=decryptionStream,proto3" json:"decryption_stream,omitempty"`
	SeqNum           uint64                 `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Length           int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResponseDecryptionStreamData) Reset() {
	*x = ResponseDecryptionStreamData{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDecryptionStreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDecryptionStreamData) ProtoMessage() {}

func (x *ResponseDecryptionStreamData) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDecryptionStreamData.ProtoReflect.Descriptor instead.
func (*ResponseDecryptionStreamData) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseDecryptionStreamData) GetDecryptionStream() []byte {
	if x != nil {
		return x.DecryptionStream
	}
	return nil
}

func (x *ResponseDecryptionStreamData) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *ResponseDecryptionStreamData) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type SignedRedactedDecryptionStream struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RedactedStream []byte                 `protobuf:"bytes,1,opt,name=redacted_stream,json=redactedStream,proto3" json:"redacted_stream,omitempty"`
	SeqNum         uint64                 `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignedRedactedDecryptionStream) Reset() {
	*x = SignedRedactedDecryptionStream{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedRedactedDecryptionStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedRedactedDecryptionStream) ProtoMessage() {}

func (x *SignedRedactedDecryptionStream) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedRedactedDecryptionStream.ProtoReflect.Descriptor instead.
func (*SignedRedactedDecryptionStream) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *SignedRedactedDecryptionStream) GetRedactedStream() []byte {
	if x != nil {
		return x.RedactedStream
	}
	return nil
}

func (x *SignedRedactedDecryptionStream) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

// Error wrapper
type ErrorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorData) Reset() {
	*x = ErrorData{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorData) ProtoMessage() {}

func (x *ErrorData) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorData.ProtoReflect.Descriptor instead.
func (*ErrorData) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Empty placeholders
type FinishedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishedMessage) Reset() {
	*x = FinishedMessage{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishedMessage) ProtoMessage() {}

func (x *FinishedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishedMessage.ProtoReflect.Descriptor instead.
func (*FinishedMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

type AttestationRequestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationRequestData) Reset() {
	*x = AttestationRequestData{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationRequestData) ProtoMessage() {}

func (x *AttestationRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationRequestData.ProtoReflect.Descriptor instead.
func (*AttestationRequestData) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\bteeproto\"\x82\x01\n" +
	"\x15RequestRedactionRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12'\n" +
	"\x0fredaction_bytes\x18\x04 \x01(\fR\x0eredactionBytes\"F\n" +
	"\x16ResponseRedactionRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\"|\n" +
	"\x1cResponseDecryptionStreamData\x12+\n" +
	"\x11decryption_stream\x18\x01 \x01(\fR\x10decryptionStream\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x04R\x06seqNum\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\"b\n" +
	"\x1eSignedRedactedDecryptionStream\x12'\n" +
	"\x0fredacted_stream\x18\x01 \x01(\fR\x0eredactedStream\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x04R\x06seqNum\"%\n" +
	"\tErrorData\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x11\n" +
	"\x0fFinishedMessage\"\x18\n" +
	"\x16AttestationRequestDataB\x18Z\x16tee-mpc/proto;teeprotob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_proto_goTypes = []any{
	(*RequestRedactionRange)(nil),          // 0: teeproto.RequestRedactionRange
	(*ResponseRedactionRange)(nil),         // 1: teeproto.ResponseRedactionRange
	(*ResponseDecryptionStreamData)(nil),   // 2: teeproto.ResponseDecryptionStreamData
	(*SignedRedactedDecryptionStream)(nil), // 3: teeproto.SignedRedactedDecryptionStream
	(*ErrorData)(nil),                      // 4: teeproto.ErrorData
	(*FinishedMessage)(nil),                // 5: teeproto.FinishedMessage
	(*AttestationRequestData)(nil),         // 6: teeproto.AttestationRequestData
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
