// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: signing.proto

package teeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Signature wrapper used everywhere
type BodyType int32

const (
	BodyType_BODY_TYPE_UNSPECIFIED BodyType = 0
	BodyType_BODY_TYPE_K_OUTPUT    BodyType = 1
	BodyType_BODY_TYPE_T_OUTPUT    BodyType = 2
)

// Enum value maps for BodyType.
var (
	BodyType_name = map[int32]string{
		0: "BODY_TYPE_UNSPECIFIED",
		1: "BODY_TYPE_K_OUTPUT",
		2: "BODY_TYPE_T_OUTPUT",
	}
	BodyType_value = map[string]int32{
		"BODY_TYPE_UNSPECIFIED": 0,
		"BODY_TYPE_K_OUTPUT":    1,
		"BODY_TYPE_T_OUTPUT":    2,
	}
)

func (x BodyType) Enum() *BodyType {
	p := new(BodyType)
	*p = x
	return p
}

func (x BodyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BodyType) Descriptor() protoreflect.EnumDescriptor {
	return file_signing_proto_enumTypes[0].Descriptor()
}

func (BodyType) Type() protoreflect.EnumType {
	return &file_signing_proto_enumTypes[0]
}

func (x BodyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BodyType.Descriptor instead.
func (BodyType) EnumDescriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{0}
}

// Deterministically serialized payloads to be signed by TEEs
type KOutputPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For single request-response mode
	RedactedRequest         []byte                            `protobuf:"bytes,1,opt,name=redacted_request,json=redactedRequest,proto3" json:"redacted_request,omitempty"` // R_red
	RequestRedactionRanges  []*RequestRedactionRange          `protobuf:"bytes,2,rep,name=request_redaction_ranges,json=requestRedactionRanges,proto3" json:"request_redaction_ranges,omitempty"`
	RedactedStreams         []*SignedRedactedDecryptionStream `protobuf:"bytes,3,rep,name=redacted_streams,json=redactedStreams,proto3" json:"redacted_streams,omitempty"` // from TEE_K
	Packets                 [][]byte                          `protobuf:"bytes,4,rep,name=packets,proto3" json:"packets,omitempty"`                                        // TLS handshake packets observed by TEE_K
	ResponseRedactionRanges []*ResponseRedactionRange         `protobuf:"bytes,5,rep,name=response_redaction_ranges,json=responseRedactionRanges,proto3" json:"response_redaction_ranges,omitempty"`
	TimestampMs             uint64                            `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // Unix timestamp in milliseconds when payload was created (SIGNED)
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *KOutputPayload) Reset() {
	*x = KOutputPayload{}
	mi := &file_signing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KOutputPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KOutputPayload) ProtoMessage() {}

func (x *KOutputPayload) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KOutputPayload.ProtoReflect.Descriptor instead.
func (*KOutputPayload) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{0}
}

func (x *KOutputPayload) GetRedactedRequest() []byte {
	if x != nil {
		return x.RedactedRequest
	}
	return nil
}

func (x *KOutputPayload) GetRequestRedactionRanges() []*RequestRedactionRange {
	if x != nil {
		return x.RequestRedactionRanges
	}
	return nil
}

func (x *KOutputPayload) GetRedactedStreams() []*SignedRedactedDecryptionStream {
	if x != nil {
		return x.RedactedStreams
	}
	return nil
}

func (x *KOutputPayload) GetPackets() [][]byte {
	if x != nil {
		return x.Packets
	}
	return nil
}

func (x *KOutputPayload) GetResponseRedactionRanges() []*ResponseRedactionRange {
	if x != nil {
		return x.ResponseRedactionRanges
	}
	return nil
}

func (x *KOutputPayload) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type TOutputPayload struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Packets             [][]byte               `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`                                                      // TLS packets observed by TEE_T
	RequestProofStreams [][]byte               `protobuf:"bytes,2,rep,name=request_proof_streams,json=requestProofStreams,proto3" json:"request_proof_streams,omitempty"` // R_SP streams signed by TEE_T for cryptographic verification
	TimestampMs         uint64                 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`                          // Unix timestamp in milliseconds when payload was created (SIGNED)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TOutputPayload) Reset() {
	*x = TOutputPayload{}
	mi := &file_signing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOutputPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOutputPayload) ProtoMessage() {}

func (x *TOutputPayload) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOutputPayload.ProtoReflect.Descriptor instead.
func (*TOutputPayload) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{1}
}

func (x *TOutputPayload) GetPackets() [][]byte {
	if x != nil {
		return x.Packets
	}
	return nil
}

func (x *TOutputPayload) GetRequestProofStreams() [][]byte {
	if x != nil {
		return x.RequestProofStreams
	}
	return nil
}

func (x *TOutputPayload) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// Attestation report with structured data
type AttestationReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`     // "nitro" or "gcp"
	Report        []byte                 `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"` // raw provider-specific attestation bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationReport) Reset() {
	*x = AttestationReport{}
	mi := &file_signing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationReport) ProtoMessage() {}

func (x *AttestationReport) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationReport.ProtoReflect.Descriptor instead.
func (*AttestationReport) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{2}
}

func (x *AttestationReport) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AttestationReport) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

type SignedMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BodyType          BodyType               `protobuf:"varint,1,opt,name=body_type,json=bodyType,proto3,enum=teeproto.BodyType" json:"body_type,omitempty"`
	Body              []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`                                                    // serialized deterministic KOutputPayload or TOutputPayload (contains signed timestamp)
	EthAddress        []byte                 `protobuf:"bytes,3,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`                      // ETH address (20 bytes, standalone mode only)
	Signature         []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                                          // signature over body bytes
	AttestationReport *AttestationReport     `protobuf:"bytes,5,opt,name=attestation_report,json=attestationReport,proto3" json:"attestation_report,omitempty"` // full attestation (enclave mode only)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignedMessage) Reset() {
	*x = SignedMessage{}
	mi := &file_signing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedMessage) ProtoMessage() {}

func (x *SignedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedMessage.ProtoReflect.Descriptor instead.
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{3}
}

func (x *SignedMessage) GetBodyType() BodyType {
	if x != nil {
		return x.BodyType
	}
	return BodyType_BODY_TYPE_UNSPECIFIED
}

func (x *SignedMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SignedMessage) GetEthAddress() []byte {
	if x != nil {
		return x.EthAddress
	}
	return nil
}

func (x *SignedMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedMessage) GetAttestationReport() *AttestationReport {
	if x != nil {
		return x.AttestationReport
	}
	return nil
}

var File_signing_proto protoreflect.FileDescriptor

const file_signing_proto_rawDesc = "" +
	"\n" +
	"\rsigning.proto\x12\bteeproto\x1a\fcommon.proto\"\x86\x03\n" +
	"\x0eKOutputPayload\x12)\n" +
	"\x10redacted_request\x18\x01 \x01(\fR\x0fredactedRequest\x12Y\n" +
	"\x18request_redaction_ranges\x18\x02 \x03(\v2\x1f.teeproto.RequestRedactionRangeR\x16requestRedactionRanges\x12S\n" +
	"\x10redacted_streams\x18\x03 \x03(\v2(.teeproto.SignedRedactedDecryptionStreamR\x0fredactedStreams\x12\x18\n" +
	"\apackets\x18\x04 \x03(\fR\apackets\x12\\\n" +
	"\x19response_redaction_ranges\x18\x05 \x03(\v2 .teeproto.ResponseRedactionRangeR\x17responseRedactionRanges\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x04R\vtimestampMs\"\x81\x01\n" +
	"\x0eTOutputPayload\x12\x18\n" +
	"\apackets\x18\x01 \x03(\fR\apackets\x122\n" +
	"\x15request_proof_streams\x18\x02 \x03(\fR\x13requestProofStreams\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x04R\vtimestampMs\"?\n" +
	"\x11AttestationReport\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06report\x18\x02 \x01(\fR\x06report\"\xdf\x01\n" +
	"\rSignedMessage\x12/\n" +
	"\tbody_type\x18\x01 \x01(\x0e2\x12.teeproto.BodyTypeR\bbodyType\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x1f\n" +
	"\veth_address\x18\x03 \x01(\fR\n" +
	"ethAddress\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12J\n" +
	"\x12attestation_report\x18\x05 \x01(\v2\x1b.teeproto.AttestationReportR\x11attestationReport*U\n" +
	"\bBodyType\x12\x19\n" +
	"\x15BODY_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12BODY_TYPE_K_OUTPUT\x10\x01\x12\x16\n" +
	"\x12BODY_TYPE_T_OUTPUT\x10\x02B\x18Z\x16tee-mpc/proto;teeprotob\x06proto3"

var (
	file_signing_proto_rawDescOnce sync.Once
	file_signing_proto_rawDescData []byte
)

func file_signing_proto_rawDescGZIP() []byte {
	file_signing_proto_rawDescOnce.Do(func() {
		file_signing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signing_proto_rawDesc), len(file_signing_proto_rawDesc)))
	})
	return file_signing_proto_rawDescData
}

var file_signing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_signing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_signing_proto_goTypes = []any{
	(BodyType)(0),                          // 0: teeproto.BodyType
	(*KOutputPayload)(nil),                 // 1: teeproto.KOutputPayload
	(*TOutputPayload)(nil),                 // 2: teeproto.TOutputPayload
	(*AttestationReport)(nil),              // 3: teeproto.AttestationReport
	(*SignedMessage)(nil),                  // 4: teeproto.SignedMessage
	(*RequestRedactionRange)(nil),          // 5: teeproto.RequestRedactionRange
	(*SignedRedactedDecryptionStream)(nil), // 6: teeproto.SignedRedactedDecryptionStream
	(*ResponseRedactionRange)(nil),         // 7: teeproto.ResponseRedactionRange
}
var file_signing_proto_depIdxs = []int32{
	5, // 0: teeproto.KOutputPayload.request_redaction_ranges:type_name -> teeproto.RequestRedactionRange
	6, // 1: teeproto.KOutputPayload.redacted_streams:type_name -> teeproto.SignedRedactedDecryptionStream
	7, // 2: teeproto.KOutputPayload.response_redaction_ranges:type_name -> teeproto.ResponseRedactionRange
	0, // 3: teeproto.SignedMessage.body_type:type_name -> teeproto.BodyType
	3, // 4: teeproto.SignedMessage.attestation_report:type_name -> teeproto.AttestationReport
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_signing_proto_init() }
func file_signing_proto_init() {
	if File_signing_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signing_proto_rawDesc), len(file_signing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signing_proto_goTypes,
		DependencyIndexes: file_signing_proto_depIdxs,
		EnumInfos:         file_signing_proto_enumTypes,
		MessageInfos:      file_signing_proto_msgTypes,
	}.Build()
	File_signing_proto = out.File
	file_signing_proto_goTypes = nil
	file_signing_proto_depIdxs = nil
}
