// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: transport.proto

package teeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sender int32

const (
	Sender_SENDER_UNSPECIFIED Sender = 0
	Sender_SENDER_USER        Sender = 1
	Sender_SENDER_TEE_K       Sender = 2
	Sender_SENDER_TEE_T       Sender = 3
)

// Enum value maps for Sender.
var (
	Sender_name = map[int32]string{
		0: "SENDER_UNSPECIFIED",
		1: "SENDER_USER",
		2: "SENDER_TEE_K",
		3: "SENDER_TEE_T",
	}
	Sender_value = map[string]int32{
		"SENDER_UNSPECIFIED": 0,
		"SENDER_USER":        1,
		"SENDER_TEE_K":       2,
		"SENDER_TEE_T":       3,
	}
)

func (x Sender) Enum() *Sender {
	p := new(Sender)
	*p = x
	return p
}

func (x Sender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sender) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_proto_enumTypes[0].Descriptor()
}

func (Sender) Type() protoreflect.EnumType {
	return &file_transport_proto_enumTypes[0]
}

func (x Sender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sender.Descriptor instead.
func (Sender) EnumDescriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0}
}

// Envelope for all websocket frames
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Sender        Sender                 `protobuf:"varint,4,opt,name=sender,proto3,enum=teeproto.Sender" json:"sender,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_ConnectionReady
	//	*Envelope_TcpReady
	//	*Envelope_Error
	//	*Envelope_Finished
	//	*Envelope_SessionCreated
	//	*Envelope_SessionReady
	//	*Envelope_RequestConnection
	//	*Envelope_TcpData
	//	*Envelope_HandshakeComplete
	//	*Envelope_HandshakeKeyDisclosure
	//	*Envelope_HttpResponse
	//	*Envelope_KeyShareRequest
	//	*Envelope_EncryptedRequest
	//	*Envelope_KeyShareResponse
	//	*Envelope_RedactedRequest
	//	*Envelope_RedactionStreams
	//	*Envelope_RedactionVerification
	//	*Envelope_ResponseRedactionSpec
	//	*Envelope_EncryptedData
	//	*Envelope_EncryptedResponse
	//	*Envelope_BatchedEncryptedResponses
	//	*Envelope_BatchedResponseLengths
	//	*Envelope_BatchedTagSecrets
	//	*Envelope_BatchedTagVerifications
	//	*Envelope_BatchedDecryptionStreams
	//	*Envelope_BatchedSignedRedactedDecryptionStreams
	//	*Envelope_AttestationRequest
	//	*Envelope_AttestationResponse
	//	*Envelope_TeetReady
	//	*Envelope_SignedMessage
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Envelope) GetSender() Sender {
	if x != nil {
		return x.Sender
	}
	return Sender_SENDER_UNSPECIFIED
}

func (x *Envelope) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetConnectionReady() *ConnectionReady {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ConnectionReady); ok {
			return x.ConnectionReady
		}
	}
	return nil
}

func (x *Envelope) GetTcpReady() *TCPReady {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TcpReady); ok {
			return x.TcpReady
		}
	}
	return nil
}

func (x *Envelope) GetError() *ErrorData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope) GetFinished() *FinishedMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Finished); ok {
			return x.Finished
		}
	}
	return nil
}

func (x *Envelope) GetSessionCreated() *SessionCreated {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SessionCreated); ok {
			return x.SessionCreated
		}
	}
	return nil
}

func (x *Envelope) GetSessionReady() *SessionReady {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SessionReady); ok {
			return x.SessionReady
		}
	}
	return nil
}

func (x *Envelope) GetRequestConnection() *RequestConnection {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RequestConnection); ok {
			return x.RequestConnection
		}
	}
	return nil
}

func (x *Envelope) GetTcpData() *TCPData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TcpData); ok {
			return x.TcpData
		}
	}
	return nil
}

func (x *Envelope) GetHandshakeComplete() *HandshakeComplete {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HandshakeComplete); ok {
			return x.HandshakeComplete
		}
	}
	return nil
}

func (x *Envelope) GetHandshakeKeyDisclosure() *HandshakeKeyDisclosure {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HandshakeKeyDisclosure); ok {
			return x.HandshakeKeyDisclosure
		}
	}
	return nil
}

func (x *Envelope) GetHttpResponse() *HTTPResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

func (x *Envelope) GetKeyShareRequest() *KeyShareRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_KeyShareRequest); ok {
			return x.KeyShareRequest
		}
	}
	return nil
}

func (x *Envelope) GetEncryptedRequest() *EncryptedRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_EncryptedRequest); ok {
			return x.EncryptedRequest
		}
	}
	return nil
}

func (x *Envelope) GetKeyShareResponse() *KeyShareResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_KeyShareResponse); ok {
			return x.KeyShareResponse
		}
	}
	return nil
}

func (x *Envelope) GetRedactedRequest() *RedactedRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RedactedRequest); ok {
			return x.RedactedRequest
		}
	}
	return nil
}

func (x *Envelope) GetRedactionStreams() *RedactionStreams {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RedactionStreams); ok {
			return x.RedactionStreams
		}
	}
	return nil
}

func (x *Envelope) GetRedactionVerification() *RedactionVerification {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RedactionVerification); ok {
			return x.RedactionVerification
		}
	}
	return nil
}

func (x *Envelope) GetResponseRedactionSpec() *ResponseRedactionSpec {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ResponseRedactionSpec); ok {
			return x.ResponseRedactionSpec
		}
	}
	return nil
}

func (x *Envelope) GetEncryptedData() *EncryptedDataResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_EncryptedData); ok {
			return x.EncryptedData
		}
	}
	return nil
}

func (x *Envelope) GetEncryptedResponse() *EncryptedResponseData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_EncryptedResponse); ok {
			return x.EncryptedResponse
		}
	}
	return nil
}

func (x *Envelope) GetBatchedEncryptedResponses() *BatchedEncryptedResponses {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_BatchedEncryptedResponses); ok {
			return x.BatchedEncryptedResponses
		}
	}
	return nil
}

func (x *Envelope) GetBatchedResponseLengths() *BatchedResponseLengths {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_BatchedResponseLengths); ok {
			return x.BatchedResponseLengths
		}
	}
	return nil
}

func (x *Envelope) GetBatchedTagSecrets() *BatchedTagSecrets {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_BatchedTagSecrets); ok {
			return x.BatchedTagSecrets
		}
	}
	return nil
}

func (x *Envelope) GetBatchedTagVerifications() *BatchedTagVerifications {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_BatchedTagVerifications); ok {
			return x.BatchedTagVerifications
		}
	}
	return nil
}

func (x *Envelope) GetBatchedDecryptionStreams() *BatchedDecryptionStreams {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_BatchedDecryptionStreams); ok {
			return x.BatchedDecryptionStreams
		}
	}
	return nil
}

func (x *Envelope) GetBatchedSignedRedactedDecryptionStreams() *BatchedSignedRedactedDecryptionStreams {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_BatchedSignedRedactedDecryptionStreams); ok {
			return x.BatchedSignedRedactedDecryptionStreams
		}
	}
	return nil
}

func (x *Envelope) GetAttestationRequest() *AttestationRequestData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AttestationRequest); ok {
			return x.AttestationRequest
		}
	}
	return nil
}

func (x *Envelope) GetAttestationResponse() *AttestationResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AttestationResponse); ok {
			return x.AttestationResponse
		}
	}
	return nil
}

func (x *Envelope) GetTeetReady() *TEETReady {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TeetReady); ok {
			return x.TeetReady
		}
	}
	return nil
}

func (x *Envelope) GetSignedMessage() *SignedMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SignedMessage); ok {
			return x.SignedMessage
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_ConnectionReady struct {
	// Session and control
	ConnectionReady *ConnectionReady `protobuf:"bytes,10,opt,name=connection_ready,json=connectionReady,proto3,oneof"`
}

type Envelope_TcpReady struct {
	TcpReady *TCPReady `protobuf:"bytes,11,opt,name=tcp_ready,json=tcpReady,proto3,oneof"`
}

type Envelope_Error struct {
	Error *ErrorData `protobuf:"bytes,12,opt,name=error,proto3,oneof"`
}

type Envelope_Finished struct {
	Finished *FinishedMessage `protobuf:"bytes,13,opt,name=finished,proto3,oneof"`
}

type Envelope_SessionCreated struct {
	SessionCreated *SessionCreated `protobuf:"bytes,14,opt,name=session_created,json=sessionCreated,proto3,oneof"`
}

type Envelope_SessionReady struct {
	SessionReady *SessionReady `protobuf:"bytes,15,opt,name=session_ready,json=sessionReady,proto3,oneof"`
}

type Envelope_RequestConnection struct {
	// Handshake
	RequestConnection *RequestConnection `protobuf:"bytes,20,opt,name=request_connection,json=requestConnection,proto3,oneof"`
}

type Envelope_TcpData struct {
	TcpData *TCPData `protobuf:"bytes,21,opt,name=tcp_data,json=tcpData,proto3,oneof"`
}

type Envelope_HandshakeComplete struct {
	HandshakeComplete *HandshakeComplete `protobuf:"bytes,22,opt,name=handshake_complete,json=handshakeComplete,proto3,oneof"`
}

type Envelope_HandshakeKeyDisclosure struct {
	HandshakeKeyDisclosure *HandshakeKeyDisclosure `protobuf:"bytes,23,opt,name=handshake_key_disclosure,json=handshakeKeyDisclosure,proto3,oneof"`
}

type Envelope_HttpResponse struct {
	HttpResponse *HTTPResponse `protobuf:"bytes,24,opt,name=http_response,json=httpResponse,proto3,oneof"`
}

type Envelope_KeyShareRequest struct {
	// Split AEAD
	KeyShareRequest *KeyShareRequest `protobuf:"bytes,30,opt,name=key_share_request,json=keyShareRequest,proto3,oneof"`
}

type Envelope_EncryptedRequest struct {
	EncryptedRequest *EncryptedRequest `protobuf:"bytes,31,opt,name=encrypted_request,json=encryptedRequest,proto3,oneof"`
}

type Envelope_KeyShareResponse struct {
	KeyShareResponse *KeyShareResponse `protobuf:"bytes,32,opt,name=key_share_response,json=keyShareResponse,proto3,oneof"`
}

type Envelope_RedactedRequest struct {
	// Redaction/TEET
	RedactedRequest *RedactedRequest `protobuf:"bytes,40,opt,name=redacted_request,json=redactedRequest,proto3,oneof"`
}

type Envelope_RedactionStreams struct {
	RedactionStreams *RedactionStreams `protobuf:"bytes,41,opt,name=redaction_streams,json=redactionStreams,proto3,oneof"`
}

type Envelope_RedactionVerification struct {
	RedactionVerification *RedactionVerification `protobuf:"bytes,44,opt,name=redaction_verification,json=redactionVerification,proto3,oneof"`
}

type Envelope_ResponseRedactionSpec struct {
	ResponseRedactionSpec *ResponseRedactionSpec `protobuf:"bytes,45,opt,name=response_redaction_spec,json=responseRedactionSpec,proto3,oneof"`
}

type Envelope_EncryptedData struct {
	EncryptedData *EncryptedDataResponse `protobuf:"bytes,42,opt,name=encrypted_data,json=encryptedData,proto3,oneof"`
}

type Envelope_EncryptedResponse struct {
	EncryptedResponse *EncryptedResponseData `protobuf:"bytes,43,opt,name=encrypted_response,json=encryptedResponse,proto3,oneof"`
}

type Envelope_BatchedEncryptedResponses struct {
	// Batches
	BatchedEncryptedResponses *BatchedEncryptedResponses `protobuf:"bytes,50,opt,name=batched_encrypted_responses,json=batchedEncryptedResponses,proto3,oneof"`
}

type Envelope_BatchedResponseLengths struct {
	BatchedResponseLengths *BatchedResponseLengths `protobuf:"bytes,51,opt,name=batched_response_lengths,json=batchedResponseLengths,proto3,oneof"`
}

type Envelope_BatchedTagSecrets struct {
	BatchedTagSecrets *BatchedTagSecrets `protobuf:"bytes,52,opt,name=batched_tag_secrets,json=batchedTagSecrets,proto3,oneof"`
}

type Envelope_BatchedTagVerifications struct {
	BatchedTagVerifications *BatchedTagVerifications `protobuf:"bytes,53,opt,name=batched_tag_verifications,json=batchedTagVerifications,proto3,oneof"`
}

type Envelope_BatchedDecryptionStreams struct {
	BatchedDecryptionStreams *BatchedDecryptionStreams `protobuf:"bytes,54,opt,name=batched_decryption_streams,json=batchedDecryptionStreams,proto3,oneof"`
}

type Envelope_BatchedSignedRedactedDecryptionStreams struct {
	BatchedSignedRedactedDecryptionStreams *BatchedSignedRedactedDecryptionStreams `protobuf:"bytes,55,opt,name=batched_signed_redacted_decryption_streams,json=batchedSignedRedactedDecryptionStreams,proto3,oneof"`
}

type Envelope_AttestationRequest struct {
	// Attestation
	AttestationRequest *AttestationRequestData `protobuf:"bytes,60,opt,name=attestation_request,json=attestationRequest,proto3,oneof"`
}

type Envelope_AttestationResponse struct {
	AttestationResponse *AttestationResponse `protobuf:"bytes,61,opt,name=attestation_response,json=attestationResponse,proto3,oneof"`
}

type Envelope_TeetReady struct {
	TeetReady *TEETReady `protobuf:"bytes,62,opt,name=teet_ready,json=teetReady,proto3,oneof"`
}

type Envelope_SignedMessage struct {
	// Signing outputs
	SignedMessage *SignedMessage `protobuf:"bytes,70,opt,name=signed_message,json=signedMessage,proto3,oneof"`
}

func (*Envelope_ConnectionReady) isEnvelope_Payload() {}

func (*Envelope_TcpReady) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

func (*Envelope_Finished) isEnvelope_Payload() {}

func (*Envelope_SessionCreated) isEnvelope_Payload() {}

func (*Envelope_SessionReady) isEnvelope_Payload() {}

func (*Envelope_RequestConnection) isEnvelope_Payload() {}

func (*Envelope_TcpData) isEnvelope_Payload() {}

func (*Envelope_HandshakeComplete) isEnvelope_Payload() {}

func (*Envelope_HandshakeKeyDisclosure) isEnvelope_Payload() {}

func (*Envelope_HttpResponse) isEnvelope_Payload() {}

func (*Envelope_KeyShareRequest) isEnvelope_Payload() {}

func (*Envelope_EncryptedRequest) isEnvelope_Payload() {}

func (*Envelope_KeyShareResponse) isEnvelope_Payload() {}

func (*Envelope_RedactedRequest) isEnvelope_Payload() {}

func (*Envelope_RedactionStreams) isEnvelope_Payload() {}

func (*Envelope_RedactionVerification) isEnvelope_Payload() {}

func (*Envelope_ResponseRedactionSpec) isEnvelope_Payload() {}

func (*Envelope_EncryptedData) isEnvelope_Payload() {}

func (*Envelope_EncryptedResponse) isEnvelope_Payload() {}

func (*Envelope_BatchedEncryptedResponses) isEnvelope_Payload() {}

func (*Envelope_BatchedResponseLengths) isEnvelope_Payload() {}

func (*Envelope_BatchedTagSecrets) isEnvelope_Payload() {}

func (*Envelope_BatchedTagVerifications) isEnvelope_Payload() {}

func (*Envelope_BatchedDecryptionStreams) isEnvelope_Payload() {}

func (*Envelope_BatchedSignedRedactedDecryptionStreams) isEnvelope_Payload() {}

func (*Envelope_AttestationRequest) isEnvelope_Payload() {}

func (*Envelope_AttestationResponse) isEnvelope_Payload() {}

func (*Envelope_TeetReady) isEnvelope_Payload() {}

func (*Envelope_SignedMessage) isEnvelope_Payload() {}

// Basic types aligned with existing JSON models
type RequestConnection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hostname         string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port             int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Sni              string                 `protobuf:"bytes,3,opt,name=sni,proto3" json:"sni,omitempty"`
	Alpn             []string               `protobuf:"bytes,4,rep,name=alpn,proto3" json:"alpn,omitempty"`
	ForceTlsVersion  string                 `protobuf:"bytes,5,opt,name=force_tls_version,json=forceTlsVersion,proto3" json:"force_tls_version,omitempty"`    // optional
	ForceCipherSuite string                 `protobuf:"bytes,6,opt,name=force_cipher_suite,json=forceCipherSuite,proto3" json:"force_cipher_suite,omitempty"` // optional (kept string form)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestConnection) Reset() {
	*x = RequestConnection{}
	mi := &file_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestConnection) ProtoMessage() {}

func (x *RequestConnection) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestConnection.ProtoReflect.Descriptor instead.
func (*RequestConnection) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{1}
}

func (x *RequestConnection) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RequestConnection) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestConnection) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *RequestConnection) GetAlpn() []string {
	if x != nil {
		return x.Alpn
	}
	return nil
}

func (x *RequestConnection) GetForceTlsVersion() string {
	if x != nil {
		return x.ForceTlsVersion
	}
	return ""
}

func (x *RequestConnection) GetForceCipherSuite() string {
	if x != nil {
		return x.ForceCipherSuite
	}
	return ""
}

type ConnectionReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionReady) Reset() {
	*x = ConnectionReady{}
	mi := &file_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionReady) ProtoMessage() {}

func (x *ConnectionReady) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionReady.ProtoReflect.Descriptor instead.
func (*ConnectionReady) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionReady) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TCPReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPReady) Reset() {
	*x = TCPReady{}
	mi := &file_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPReady) ProtoMessage() {}

func (x *TCPReady) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPReady.ProtoReflect.Descriptor instead.
func (*TCPReady) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{3}
}

func (x *TCPReady) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TCPData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPData) Reset() {
	*x = TCPData{}
	mi := &file_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPData) ProtoMessage() {}

func (x *TCPData) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPData.ProtoReflect.Descriptor instead.
func (*TCPData) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{4}
}

func (x *TCPData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HandshakeComplete struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CertificateChain [][]byte               `protobuf:"bytes,2,rep,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandshakeComplete) Reset() {
	*x = HandshakeComplete{}
	mi := &file_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeComplete) ProtoMessage() {}

func (x *HandshakeComplete) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeComplete.ProtoReflect.Descriptor instead.
func (*HandshakeComplete) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{5}
}

func (x *HandshakeComplete) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandshakeComplete) GetCertificateChain() [][]byte {
	if x != nil {
		return x.CertificateChain
	}
	return nil
}

type HandshakeKeyDisclosure struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HandshakeKey      []byte                 `protobuf:"bytes,1,opt,name=handshake_key,json=handshakeKey,proto3" json:"handshake_key,omitempty"`
	HandshakeIv       []byte                 `protobuf:"bytes,2,opt,name=handshake_iv,json=handshakeIv,proto3" json:"handshake_iv,omitempty"`
	CertificatePacket []byte                 `protobuf:"bytes,3,opt,name=certificate_packet,json=certificatePacket,proto3" json:"certificate_packet,omitempty"`
	CipherSuite       uint32                 `protobuf:"varint,4,opt,name=cipher_suite,json=cipherSuite,proto3" json:"cipher_suite,omitempty"` // uint16 fits here
	Algorithm         string                 `protobuf:"bytes,5,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Success           bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HandshakeKeyDisclosure) Reset() {
	*x = HandshakeKeyDisclosure{}
	mi := &file_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeKeyDisclosure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeKeyDisclosure) ProtoMessage() {}

func (x *HandshakeKeyDisclosure) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeKeyDisclosure.ProtoReflect.Descriptor instead.
func (*HandshakeKeyDisclosure) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{6}
}

func (x *HandshakeKeyDisclosure) GetHandshakeKey() []byte {
	if x != nil {
		return x.HandshakeKey
	}
	return nil
}

func (x *HandshakeKeyDisclosure) GetHandshakeIv() []byte {
	if x != nil {
		return x.HandshakeIv
	}
	return nil
}

func (x *HandshakeKeyDisclosure) GetCertificatePacket() []byte {
	if x != nil {
		return x.CertificatePacket
	}
	return nil
}

func (x *HandshakeKeyDisclosure) GetCipherSuite() uint32 {
	if x != nil {
		return x.CipherSuite
	}
	return 0
}

func (x *HandshakeKeyDisclosure) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *HandshakeKeyDisclosure) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"` // optional
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponse) Reset() {
	*x = HTTPResponse{}
	mi := &file_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponse) ProtoMessage() {}

func (x *HTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponse.ProtoReflect.Descriptor instead.
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{7}
}

func (x *HTTPResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *HTTPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type KeyShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CipherSuite   uint32                 `protobuf:"varint,1,opt,name=cipher_suite,json=cipherSuite,proto3" json:"cipher_suite,omitempty"` // uint16 fits here
	KeyLength     int32                  `protobuf:"varint,2,opt,name=key_length,json=keyLength,proto3" json:"key_length,omitempty"`
	IvLength      int32                  `protobuf:"varint,3,opt,name=iv_length,json=ivLength,proto3" json:"iv_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyShareRequest) Reset() {
	*x = KeyShareRequest{}
	mi := &file_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyShareRequest) ProtoMessage() {}

func (x *KeyShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyShareRequest.ProtoReflect.Descriptor instead.
func (*KeyShareRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{8}
}

func (x *KeyShareRequest) GetCipherSuite() uint32 {
	if x != nil {
		return x.CipherSuite
	}
	return 0
}

func (x *KeyShareRequest) GetKeyLength() int32 {
	if x != nil {
		return x.KeyLength
	}
	return 0
}

func (x *KeyShareRequest) GetIvLength() int32 {
	if x != nil {
		return x.IvLength
	}
	return 0
}

type KeyShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyShare      []byte                 `protobuf:"bytes,1,opt,name=key_share,json=keyShare,proto3" json:"key_share,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyShareResponse) Reset() {
	*x = KeyShareResponse{}
	mi := &file_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyShareResponse) ProtoMessage() {}

func (x *KeyShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyShareResponse.ProtoReflect.Descriptor instead.
func (*KeyShareResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{9}
}

func (x *KeyShareResponse) GetKeyShare() []byte {
	if x != nil {
		return x.KeyShare
	}
	return nil
}

func (x *KeyShareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EncryptedDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedData []byte                 `protobuf:"bytes,1,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"` // R_Enc
	AuthTag       []byte                 `protobuf:"bytes,2,opt,name=auth_tag,json=authTag,proto3" json:"auth_tag,omitempty"`                   // T
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedDataResponse) Reset() {
	*x = EncryptedDataResponse{}
	mi := &file_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedDataResponse) ProtoMessage() {}

func (x *EncryptedDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedDataResponse.ProtoReflect.Descriptor instead.
func (*EncryptedDataResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{10}
}

func (x *EncryptedDataResponse) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *EncryptedDataResponse) GetAuthTag() []byte {
	if x != nil {
		return x.AuthTag
	}
	return nil
}

func (x *EncryptedDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TEETReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TEETReady) Reset() {
	*x = TEETReady{}
	mi := &file_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TEETReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TEETReady) ProtoMessage() {}

func (x *TEETReady) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TEETReady.ProtoReflect.Descriptor instead.
func (*TEETReady) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{11}
}

func (x *TEETReady) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RedactedRequest struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	RedactedRequest []byte                   `protobuf:"bytes,1,opt,name=redacted_request,json=redactedRequest,proto3" json:"redacted_request,omitempty"` // R_red
	Commitments     [][]byte                 `protobuf:"bytes,2,rep,name=commitments,proto3" json:"commitments,omitempty"`                                // [comm_s, comm_sp]
	RedactionRanges []*RequestRedactionRange `protobuf:"bytes,3,rep,name=redaction_ranges,json=redactionRanges,proto3" json:"redaction_ranges,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RedactedRequest) Reset() {
	*x = RedactedRequest{}
	mi := &file_transport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactedRequest) ProtoMessage() {}

func (x *RedactedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactedRequest.ProtoReflect.Descriptor instead.
func (*RedactedRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{12}
}

func (x *RedactedRequest) GetRedactedRequest() []byte {
	if x != nil {
		return x.RedactedRequest
	}
	return nil
}

func (x *RedactedRequest) GetCommitments() [][]byte {
	if x != nil {
		return x.Commitments
	}
	return nil
}

func (x *RedactedRequest) GetRedactionRanges() []*RequestRedactionRange {
	if x != nil {
		return x.RedactionRanges
	}
	return nil
}

type RedactionVerification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedactionVerification) Reset() {
	*x = RedactionVerification{}
	mi := &file_transport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactionVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactionVerification) ProtoMessage() {}

func (x *RedactionVerification) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactionVerification.ProtoReflect.Descriptor instead.
func (*RedactionVerification) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{13}
}

func (x *RedactionVerification) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RedactionVerification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RedactionStreams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Streams        [][]byte               `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`                                     // [Str_S, Str_SP]
	CommitmentKeys [][]byte               `protobuf:"bytes,2,rep,name=commitment_keys,json=commitmentKeys,proto3" json:"commitment_keys,omitempty"` // [K_S, K_SP]
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RedactionStreams) Reset() {
	*x = RedactionStreams{}
	mi := &file_transport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactionStreams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactionStreams) ProtoMessage() {}

func (x *RedactionStreams) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactionStreams.ProtoReflect.Descriptor instead.
func (*RedactionStreams) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{14}
}

func (x *RedactionStreams) GetStreams() [][]byte {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *RedactionStreams) GetCommitmentKeys() [][]byte {
	if x != nil {
		return x.CommitmentKeys
	}
	return nil
}

// Client to TEE_K: response redaction specification
type ResponseRedactionSpec struct {
	state                      protoimpl.MessageState    `protogen:"open.v1"`
	Ranges                     []*ResponseRedactionRange `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	AlwaysRedactSessionTickets bool                      `protobuf:"varint,2,opt,name=always_redact_session_tickets,json=alwaysRedactSessionTickets,proto3" json:"always_redact_session_tickets,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ResponseRedactionSpec) Reset() {
	*x = ResponseRedactionSpec{}
	mi := &file_transport_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseRedactionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRedactionSpec) ProtoMessage() {}

func (x *ResponseRedactionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRedactionSpec.ProtoReflect.Descriptor instead.
func (*ResponseRedactionSpec) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{15}
}

func (x *ResponseRedactionSpec) GetRanges() []*ResponseRedactionRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *ResponseRedactionSpec) GetAlwaysRedactSessionTickets() bool {
	if x != nil {
		return x.AlwaysRedactSessionTickets
	}
	return false
}

type EncryptedRequest struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	EncryptedData   []byte                   `protobuf:"bytes,1,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"` // R_red_Enc
	TagSecrets      []byte                   `protobuf:"bytes,2,opt,name=tag_secrets,json=tagSecrets,proto3" json:"tag_secrets,omitempty"`
	Commitments     [][]byte                 `protobuf:"bytes,3,rep,name=commitments,proto3" json:"commitments,omitempty"`                     // [comm_s, comm_sp]
	CipherSuite     uint32                   `protobuf:"varint,4,opt,name=cipher_suite,json=cipherSuite,proto3" json:"cipher_suite,omitempty"` // uint16 fits here
	SeqNum          uint64                   `protobuf:"varint,5,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	RedactionRanges []*RequestRedactionRange `protobuf:"bytes,6,rep,name=redaction_ranges,json=redactionRanges,proto3" json:"redaction_ranges,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EncryptedRequest) Reset() {
	*x = EncryptedRequest{}
	mi := &file_transport_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedRequest) ProtoMessage() {}

func (x *EncryptedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedRequest.ProtoReflect.Descriptor instead.
func (*EncryptedRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{16}
}

func (x *EncryptedRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *EncryptedRequest) GetTagSecrets() []byte {
	if x != nil {
		return x.TagSecrets
	}
	return nil
}

func (x *EncryptedRequest) GetCommitments() [][]byte {
	if x != nil {
		return x.Commitments
	}
	return nil
}

func (x *EncryptedRequest) GetCipherSuite() uint32 {
	if x != nil {
		return x.CipherSuite
	}
	return 0
}

func (x *EncryptedRequest) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *EncryptedRequest) GetRedactionRanges() []*RequestRedactionRange {
	if x != nil {
		return x.RedactionRanges
	}
	return nil
}

type EncryptedResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedData []byte                 `protobuf:"bytes,1,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"` // payload (without tag)
	Tag           []byte                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`                                          // auth tag
	RecordHeader  []byte                 `protobuf:"bytes,3,opt,name=record_header,json=recordHeader,proto3" json:"record_header,omitempty"`    // 5 bytes
	SeqNum        uint64                 `protobuf:"varint,4,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	ExplicitIv    []byte                 `protobuf:"bytes,5,opt,name=explicit_iv,json=explicitIv,proto3" json:"explicit_iv,omitempty"` // optional (tls1.2)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedResponseData) Reset() {
	*x = EncryptedResponseData{}
	mi := &file_transport_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedResponseData) ProtoMessage() {}

func (x *EncryptedResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedResponseData.ProtoReflect.Descriptor instead.
func (*EncryptedResponseData) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{17}
}

func (x *EncryptedResponseData) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *EncryptedResponseData) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *EncryptedResponseData) GetRecordHeader() []byte {
	if x != nil {
		return x.RecordHeader
	}
	return nil
}

func (x *EncryptedResponseData) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *EncryptedResponseData) GetExplicitIv() []byte {
	if x != nil {
		return x.ExplicitIv
	}
	return nil
}

type ResponseTagVerification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SeqNum        uint64                 `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseTagVerification) Reset() {
	*x = ResponseTagVerification{}
	mi := &file_transport_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseTagVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseTagVerification) ProtoMessage() {}

func (x *ResponseTagVerification) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseTagVerification.ProtoReflect.Descriptor instead.
func (*ResponseTagVerification) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{18}
}

func (x *ResponseTagVerification) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseTagVerification) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *ResponseTagVerification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Batches
type BatchedEncryptedResponses struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Responses     []*EncryptedResponseData `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	SessionId     string                   `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalCount    int32                    `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedEncryptedResponses) Reset() {
	*x = BatchedEncryptedResponses{}
	mi := &file_transport_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedEncryptedResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedEncryptedResponses) ProtoMessage() {}

func (x *BatchedEncryptedResponses) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedEncryptedResponses.ProtoReflect.Descriptor instead.
func (*BatchedEncryptedResponses) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{19}
}

func (x *BatchedEncryptedResponses) GetResponses() []*EncryptedResponseData {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchedEncryptedResponses) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BatchedEncryptedResponses) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type BatchedResponseLengths struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Lengths       []*BatchedResponseLengths_Length `protobuf:"bytes,1,rep,name=lengths,proto3" json:"lengths,omitempty"`
	SessionId     string                           `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalCount    int32                            `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedResponseLengths) Reset() {
	*x = BatchedResponseLengths{}
	mi := &file_transport_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedResponseLengths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedResponseLengths) ProtoMessage() {}

func (x *BatchedResponseLengths) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedResponseLengths.ProtoReflect.Descriptor instead.
func (*BatchedResponseLengths) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{20}
}

func (x *BatchedResponseLengths) GetLengths() []*BatchedResponseLengths_Length {
	if x != nil {
		return x.Lengths
	}
	return nil
}

func (x *BatchedResponseLengths) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BatchedResponseLengths) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type BatchedTagSecrets struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	TagSecrets    []*BatchedTagSecrets_TagSecret `protobuf:"bytes,1,rep,name=tag_secrets,json=tagSecrets,proto3" json:"tag_secrets,omitempty"`
	SessionId     string                         `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalCount    int32                          `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedTagSecrets) Reset() {
	*x = BatchedTagSecrets{}
	mi := &file_transport_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedTagSecrets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedTagSecrets) ProtoMessage() {}

func (x *BatchedTagSecrets) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedTagSecrets.ProtoReflect.Descriptor instead.
func (*BatchedTagSecrets) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{21}
}

func (x *BatchedTagSecrets) GetTagSecrets() []*BatchedTagSecrets_TagSecret {
	if x != nil {
		return x.TagSecrets
	}
	return nil
}

func (x *BatchedTagSecrets) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BatchedTagSecrets) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type BatchedTagVerifications struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Verifications []*BatchedTagVerifications_Verification `protobuf:"bytes,1,rep,name=verifications,proto3" json:"verifications,omitempty"`
	SessionId     string                                  `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalCount    int32                                   `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	AllSuccessful bool                                    `protobuf:"varint,4,opt,name=all_successful,json=allSuccessful,proto3" json:"all_successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedTagVerifications) Reset() {
	*x = BatchedTagVerifications{}
	mi := &file_transport_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedTagVerifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedTagVerifications) ProtoMessage() {}

func (x *BatchedTagVerifications) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedTagVerifications.ProtoReflect.Descriptor instead.
func (*BatchedTagVerifications) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{22}
}

func (x *BatchedTagVerifications) GetVerifications() []*BatchedTagVerifications_Verification {
	if x != nil {
		return x.Verifications
	}
	return nil
}

func (x *BatchedTagVerifications) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BatchedTagVerifications) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *BatchedTagVerifications) GetAllSuccessful() bool {
	if x != nil {
		return x.AllSuccessful
	}
	return false
}

type BatchedDecryptionStreams struct {
	state             protoimpl.MessageState          `protogen:"open.v1"`
	DecryptionStreams []*ResponseDecryptionStreamData `protobuf:"bytes,1,rep,name=decryption_streams,json=decryptionStreams,proto3" json:"decryption_streams,omitempty"`
	SessionId         string                          `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalCount        int32                           `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BatchedDecryptionStreams) Reset() {
	*x = BatchedDecryptionStreams{}
	mi := &file_transport_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedDecryptionStreams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedDecryptionStreams) ProtoMessage() {}

func (x *BatchedDecryptionStreams) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedDecryptionStreams.ProtoReflect.Descriptor instead.
func (*BatchedDecryptionStreams) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{23}
}

func (x *BatchedDecryptionStreams) GetDecryptionStreams() []*ResponseDecryptionStreamData {
	if x != nil {
		return x.DecryptionStreams
	}
	return nil
}

func (x *BatchedDecryptionStreams) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BatchedDecryptionStreams) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type BatchedSignedRedactedDecryptionStreams struct {
	state                 protoimpl.MessageState            `protogen:"open.v1"`
	SignedRedactedStreams []*SignedRedactedDecryptionStream `protobuf:"bytes,1,rep,name=signed_redacted_streams,json=signedRedactedStreams,proto3" json:"signed_redacted_streams,omitempty"`
	SessionId             string                            `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalCount            int32                             `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BatchedSignedRedactedDecryptionStreams) Reset() {
	*x = BatchedSignedRedactedDecryptionStreams{}
	mi := &file_transport_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedSignedRedactedDecryptionStreams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedSignedRedactedDecryptionStreams) ProtoMessage() {}

func (x *BatchedSignedRedactedDecryptionStreams) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedSignedRedactedDecryptionStreams.ProtoReflect.Descriptor instead.
func (*BatchedSignedRedactedDecryptionStreams) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{24}
}

func (x *BatchedSignedRedactedDecryptionStreams) GetSignedRedactedStreams() []*SignedRedactedDecryptionStream {
	if x != nil {
		return x.SignedRedactedStreams
	}
	return nil
}

func (x *BatchedSignedRedactedDecryptionStreams) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BatchedSignedRedactedDecryptionStreams) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Attestation
type AttestationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AttestationDoc    []byte                 `protobuf:"bytes,1,opt,name=attestation_doc,json=attestationDoc,proto3" json:"attestation_doc,omitempty"`          // deprecated: raw bytes (for backwards compatibility)
	AttestationReport *AttestationReport     `protobuf:"bytes,5,opt,name=attestation_report,json=attestationReport,proto3" json:"attestation_report,omitempty"` // structured report (from signing.proto)
	Success           bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Source            string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // "tee_k" or "tee_t"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttestationResponse) Reset() {
	*x = AttestationResponse{}
	mi := &file_transport_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationResponse) ProtoMessage() {}

func (x *AttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationResponse.ProtoReflect.Descriptor instead.
func (*AttestationResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{25}
}

func (x *AttestationResponse) GetAttestationDoc() []byte {
	if x != nil {
		return x.AttestationDoc
	}
	return nil
}

func (x *AttestationResponse) GetAttestationReport() *AttestationReport {
	if x != nil {
		return x.AttestationReport
	}
	return nil
}

func (x *AttestationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AttestationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AttestationResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type SessionCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreated) Reset() {
	*x = SessionCreated{}
	mi := &file_transport_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreated) ProtoMessage() {}

func (x *SessionCreated) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreated.ProtoReflect.Descriptor instead.
func (*SessionCreated) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{26}
}

type SessionReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReady) Reset() {
	*x = SessionReady{}
	mi := &file_transport_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReady) ProtoMessage() {}

func (x *SessionReady) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReady.ProtoReflect.Descriptor instead.
func (*SessionReady) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{27}
}

func (x *SessionReady) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type BatchedResponseLengths_Length struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	RecordHeader  []byte                 `protobuf:"bytes,2,opt,name=record_header,json=recordHeader,proto3" json:"record_header,omitempty"`
	SeqNum        uint64                 `protobuf:"varint,3,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	ExplicitIv    []byte                 `protobuf:"bytes,4,opt,name=explicit_iv,json=explicitIv,proto3" json:"explicit_iv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedResponseLengths_Length) Reset() {
	*x = BatchedResponseLengths_Length{}
	mi := &file_transport_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedResponseLengths_Length) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedResponseLengths_Length) ProtoMessage() {}

func (x *BatchedResponseLengths_Length) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedResponseLengths_Length.ProtoReflect.Descriptor instead.
func (*BatchedResponseLengths_Length) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{20, 0}
}

func (x *BatchedResponseLengths_Length) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *BatchedResponseLengths_Length) GetRecordHeader() []byte {
	if x != nil {
		return x.RecordHeader
	}
	return nil
}

func (x *BatchedResponseLengths_Length) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *BatchedResponseLengths_Length) GetExplicitIv() []byte {
	if x != nil {
		return x.ExplicitIv
	}
	return nil
}

type BatchedTagSecrets_TagSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagSecrets    []byte                 `protobuf:"bytes,1,opt,name=tag_secrets,json=tagSecrets,proto3" json:"tag_secrets,omitempty"`
	SeqNum        uint64                 `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedTagSecrets_TagSecret) Reset() {
	*x = BatchedTagSecrets_TagSecret{}
	mi := &file_transport_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedTagSecrets_TagSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedTagSecrets_TagSecret) ProtoMessage() {}

func (x *BatchedTagSecrets_TagSecret) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedTagSecrets_TagSecret.ProtoReflect.Descriptor instead.
func (*BatchedTagSecrets_TagSecret) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{21, 0}
}

func (x *BatchedTagSecrets_TagSecret) GetTagSecrets() []byte {
	if x != nil {
		return x.TagSecrets
	}
	return nil
}

func (x *BatchedTagSecrets_TagSecret) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

type BatchedTagVerifications_Verification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SeqNum        uint64                 `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedTagVerifications_Verification) Reset() {
	*x = BatchedTagVerifications_Verification{}
	mi := &file_transport_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedTagVerifications_Verification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedTagVerifications_Verification) ProtoMessage() {}

func (x *BatchedTagVerifications_Verification) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedTagVerifications_Verification.ProtoReflect.Descriptor instead.
func (*BatchedTagVerifications_Verification) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{22, 0}
}

func (x *BatchedTagVerifications_Verification) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchedTagVerifications_Verification) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *BatchedTagVerifications_Verification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_transport_proto protoreflect.FileDescriptor

const file_transport_proto_rawDesc = "" +
	"\n" +
	"\x0ftransport.proto\x12\bteeproto\x1a\fcommon.proto\x1a\rsigning.proto\"\xd7\x13\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12(\n" +
	"\x06sender\x18\x04 \x01(\x0e2\x10.teeproto.SenderR\x06sender\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x12F\n" +
	"\x10connection_ready\x18\n" +
	" \x01(\v2\x19.teeproto.ConnectionReadyH\x00R\x0fconnectionReady\x121\n" +
	"\ttcp_ready\x18\v \x01(\v2\x12.teeproto.TCPReadyH\x00R\btcpReady\x12+\n" +
	"\x05error\x18\f \x01(\v2\x13.teeproto.ErrorDataH\x00R\x05error\x127\n" +
	"\bfinished\x18\r \x01(\v2\x19.teeproto.FinishedMessageH\x00R\bfinished\x12C\n" +
	"\x0fsession_created\x18\x0e \x01(\v2\x18.teeproto.SessionCreatedH\x00R\x0esessionCreated\x12=\n" +
	"\rsession_ready\x18\x0f \x01(\v2\x16.teeproto.SessionReadyH\x00R\fsessionReady\x12L\n" +
	"\x12request_connection\x18\x14 \x01(\v2\x1b.teeproto.RequestConnectionH\x00R\x11requestConnection\x12.\n" +
	"\btcp_data\x18\x15 \x01(\v2\x11.teeproto.TCPDataH\x00R\atcpData\x12L\n" +
	"\x12handshake_complete\x18\x16 \x01(\v2\x1b.teeproto.HandshakeCompleteH\x00R\x11handshakeComplete\x12\\\n" +
	"\x18handshake_key_disclosure\x18\x17 \x01(\v2 .teeproto.HandshakeKeyDisclosureH\x00R\x16handshakeKeyDisclosure\x12=\n" +
	"\rhttp_response\x18\x18 \x01(\v2\x16.teeproto.HTTPResponseH\x00R\fhttpResponse\x12G\n" +
	"\x11key_share_request\x18\x1e \x01(\v2\x19.teeproto.KeyShareRequestH\x00R\x0fkeyShareRequest\x12I\n" +
	"\x11encrypted_request\x18\x1f \x01(\v2\x1a.teeproto.EncryptedRequestH\x00R\x10encryptedRequest\x12J\n" +
	"\x12key_share_response\x18  \x01(\v2\x1a.teeproto.KeyShareResponseH\x00R\x10keyShareResponse\x12F\n" +
	"\x10redacted_request\x18( \x01(\v2\x19.teeproto.RedactedRequestH\x00R\x0fredactedRequest\x12I\n" +
	"\x11redaction_streams\x18) \x01(\v2\x1a.teeproto.RedactionStreamsH\x00R\x10redactionStreams\x12X\n" +
	"\x16redaction_verification\x18, \x01(\v2\x1f.teeproto.RedactionVerificationH\x00R\x15redactionVerification\x12Y\n" +
	"\x17response_redaction_spec\x18- \x01(\v2\x1f.teeproto.ResponseRedactionSpecH\x00R\x15responseRedactionSpec\x12H\n" +
	"\x0eencrypted_data\x18* \x01(\v2\x1f.teeproto.EncryptedDataResponseH\x00R\rencryptedData\x12P\n" +
	"\x12encrypted_response\x18+ \x01(\v2\x1f.teeproto.EncryptedResponseDataH\x00R\x11encryptedResponse\x12e\n" +
	"\x1bbatched_encrypted_responses\x182 \x01(\v2#.teeproto.BatchedEncryptedResponsesH\x00R\x19batchedEncryptedResponses\x12\\\n" +
	"\x18batched_response_lengths\x183 \x01(\v2 .teeproto.BatchedResponseLengthsH\x00R\x16batchedResponseLengths\x12M\n" +
	"\x13batched_tag_secrets\x184 \x01(\v2\x1b.teeproto.BatchedTagSecretsH\x00R\x11batchedTagSecrets\x12_\n" +
	"\x19batched_tag_verifications\x185 \x01(\v2!.teeproto.BatchedTagVerificationsH\x00R\x17batchedTagVerifications\x12b\n" +
	"\x1abatched_decryption_streams\x186 \x01(\v2\".teeproto.BatchedDecryptionStreamsH\x00R\x18batchedDecryptionStreams\x12\x8e\x01\n" +
	"*batched_signed_redacted_decryption_streams\x187 \x01(\v20.teeproto.BatchedSignedRedactedDecryptionStreamsH\x00R&batchedSignedRedactedDecryptionStreams\x12S\n" +
	"\x13attestation_request\x18< \x01(\v2 .teeproto.AttestationRequestDataH\x00R\x12attestationRequest\x12R\n" +
	"\x14attestation_response\x18= \x01(\v2\x1d.teeproto.AttestationResponseH\x00R\x13attestationResponse\x124\n" +
	"\n" +
	"teet_ready\x18> \x01(\v2\x13.teeproto.TEETReadyH\x00R\tteetReady\x12@\n" +
	"\x0esigned_message\x18F \x01(\v2\x17.teeproto.SignedMessageH\x00R\rsignedMessageB\t\n" +
	"\apayload\"\xc3\x01\n" +
	"\x11RequestConnection\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x10\n" +
	"\x03sni\x18\x03 \x01(\tR\x03sni\x12\x12\n" +
	"\x04alpn\x18\x04 \x03(\tR\x04alpn\x12*\n" +
	"\x11force_tls_version\x18\x05 \x01(\tR\x0fforceTlsVersion\x12,\n" +
	"\x12force_cipher_suite\x18\x06 \x01(\tR\x10forceCipherSuite\"+\n" +
	"\x0fConnectionReady\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\bTCPReady\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1d\n" +
	"\aTCPData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"Z\n" +
	"\x11HandshakeComplete\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x11certificate_chain\x18\x02 \x03(\fR\x10certificateChain\"\xea\x01\n" +
	"\x16HandshakeKeyDisclosure\x12#\n" +
	"\rhandshake_key\x18\x01 \x01(\fR\fhandshakeKey\x12!\n" +
	"\fhandshake_iv\x18\x02 \x01(\fR\vhandshakeIv\x12-\n" +
	"\x12certificate_packet\x18\x03 \x01(\fR\x11certificatePacket\x12!\n" +
	"\fcipher_suite\x18\x04 \x01(\rR\vcipherSuite\x12\x1c\n" +
	"\talgorithm\x18\x05 \x01(\tR\talgorithm\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\"D\n" +
	"\fHTTPResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"p\n" +
	"\x0fKeyShareRequest\x12!\n" +
	"\fcipher_suite\x18\x01 \x01(\rR\vcipherSuite\x12\x1d\n" +
	"\n" +
	"key_length\x18\x02 \x01(\x05R\tkeyLength\x12\x1b\n" +
	"\tiv_length\x18\x03 \x01(\x05R\bivLength\"I\n" +
	"\x10KeyShareResponse\x12\x1b\n" +
	"\tkey_share\x18\x01 \x01(\fR\bkeyShare\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"s\n" +
	"\x15EncryptedDataResponse\x12%\n" +
	"\x0eencrypted_data\x18\x01 \x01(\fR\rencryptedData\x12\x19\n" +
	"\bauth_tag\x18\x02 \x01(\fR\aauthTag\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"%\n" +
	"\tTEETReady\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xaa\x01\n" +
	"\x0fRedactedRequest\x12)\n" +
	"\x10redacted_request\x18\x01 \x01(\fR\x0fredactedRequest\x12 \n" +
	"\vcommitments\x18\x02 \x03(\fR\vcommitments\x12J\n" +
	"\x10redaction_ranges\x18\x03 \x03(\v2\x1f.teeproto.RequestRedactionRangeR\x0fredactionRanges\"K\n" +
	"\x15RedactionVerification\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\x10RedactionStreams\x12\x18\n" +
	"\astreams\x18\x01 \x03(\fR\astreams\x12'\n" +
	"\x0fcommitment_keys\x18\x02 \x03(\fR\x0ecommitmentKeys\"\x94\x01\n" +
	"\x15ResponseRedactionSpec\x128\n" +
	"\x06ranges\x18\x01 \x03(\v2 .teeproto.ResponseRedactionRangeR\x06ranges\x12A\n" +
	"\x1dalways_redact_session_tickets\x18\x02 \x01(\bR\x1aalwaysRedactSessionTickets\"\x84\x02\n" +
	"\x10EncryptedRequest\x12%\n" +
	"\x0eencrypted_data\x18\x01 \x01(\fR\rencryptedData\x12\x1f\n" +
	"\vtag_secrets\x18\x02 \x01(\fR\n" +
	"tagSecrets\x12 \n" +
	"\vcommitments\x18\x03 \x03(\fR\vcommitments\x12!\n" +
	"\fcipher_suite\x18\x04 \x01(\rR\vcipherSuite\x12\x17\n" +
	"\aseq_num\x18\x05 \x01(\x04R\x06seqNum\x12J\n" +
	"\x10redaction_ranges\x18\x06 \x03(\v2\x1f.teeproto.RequestRedactionRangeR\x0fredactionRanges\"\xaf\x01\n" +
	"\x15EncryptedResponseData\x12%\n" +
	"\x0eencrypted_data\x18\x01 \x01(\fR\rencryptedData\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\fR\x03tag\x12#\n" +
	"\rrecord_header\x18\x03 \x01(\fR\frecordHeader\x12\x17\n" +
	"\aseq_num\x18\x04 \x01(\x04R\x06seqNum\x12\x1f\n" +
	"\vexplicit_iv\x18\x05 \x01(\fR\n" +
	"explicitIv\"f\n" +
	"\x17ResponseTagVerification\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x04R\x06seqNum\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9a\x01\n" +
	"\x19BatchedEncryptedResponses\x12=\n" +
	"\tresponses\x18\x01 \x03(\v2\x1f.teeproto.EncryptedResponseDataR\tresponses\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\x9c\x02\n" +
	"\x16BatchedResponseLengths\x12A\n" +
	"\alengths\x18\x01 \x03(\v2'.teeproto.BatchedResponseLengths.LengthR\alengths\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x1a\x7f\n" +
	"\x06Length\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\x12#\n" +
	"\rrecord_header\x18\x02 \x01(\fR\frecordHeader\x12\x17\n" +
	"\aseq_num\x18\x03 \x01(\x04R\x06seqNum\x12\x1f\n" +
	"\vexplicit_iv\x18\x04 \x01(\fR\n" +
	"explicitIv\"\xe2\x01\n" +
	"\x11BatchedTagSecrets\x12F\n" +
	"\vtag_secrets\x18\x01 \x03(\v2%.teeproto.BatchedTagSecrets.TagSecretR\n" +
	"tagSecrets\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x1aE\n" +
	"\tTagSecret\x12\x1f\n" +
	"\vtag_secrets\x18\x01 \x01(\fR\n" +
	"tagSecrets\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x04R\x06seqNum\"\xb3\x02\n" +
	"\x17BatchedTagVerifications\x12T\n" +
	"\rverifications\x18\x01 \x03(\v2..teeproto.BatchedTagVerifications.VerificationR\rverifications\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12%\n" +
	"\x0eall_successful\x18\x04 \x01(\bR\rallSuccessful\x1a[\n" +
	"\fVerification\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x04R\x06seqNum\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb1\x01\n" +
	"\x18BatchedDecryptionStreams\x12U\n" +
	"\x12decryption_streams\x18\x01 \x03(\v2&.teeproto.ResponseDecryptionStreamDataR\x11decryptionStreams\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xca\x01\n" +
	"&BatchedSignedRedactedDecryptionStreams\x12`\n" +
	"\x17signed_redacted_streams\x18\x01 \x03(\v2(.teeproto.SignedRedactedDecryptionStreamR\x15signedRedactedStreams\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xe1\x01\n" +
	"\x13AttestationResponse\x12'\n" +
	"\x0fattestation_doc\x18\x01 \x01(\fR\x0eattestationDoc\x12J\n" +
	"\x12attestation_report\x18\x05 \x01(\v2\x1b.teeproto.AttestationReportR\x11attestationReport\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\x10\n" +
	"\x0eSessionCreated\"$\n" +
	"\fSessionReady\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready*U\n" +
	"\x06Sender\x12\x16\n" +
	"\x12SENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSENDER_USER\x10\x01\x12\x10\n" +
	"\fSENDER_TEE_K\x10\x02\x12\x10\n" +
	"\fSENDER_TEE_T\x10\x03B\x18Z\x16tee-mpc/proto;teeprotob\x06proto3"

var (
	file_transport_proto_rawDescOnce sync.Once
	file_transport_proto_rawDescData []byte
)

func file_transport_proto_rawDescGZIP() []byte {
	file_transport_proto_rawDescOnce.Do(func() {
		file_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)))
	})
	return file_transport_proto_rawDescData
}

var file_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_transport_proto_goTypes = []any{
	(Sender)(0),                                    // 0: teeproto.Sender
	(*Envelope)(nil),                               // 1: teeproto.Envelope
	(*RequestConnection)(nil),                      // 2: teeproto.RequestConnection
	(*ConnectionReady)(nil),                        // 3: teeproto.ConnectionReady
	(*TCPReady)(nil),                               // 4: teeproto.TCPReady
	(*TCPData)(nil),                                // 5: teeproto.TCPData
	(*HandshakeComplete)(nil),                      // 6: teeproto.HandshakeComplete
	(*HandshakeKeyDisclosure)(nil),                 // 7: teeproto.HandshakeKeyDisclosure
	(*HTTPResponse)(nil),                           // 8: teeproto.HTTPResponse
	(*KeyShareRequest)(nil),                        // 9: teeproto.KeyShareRequest
	(*KeyShareResponse)(nil),                       // 10: teeproto.KeyShareResponse
	(*EncryptedDataResponse)(nil),                  // 11: teeproto.EncryptedDataResponse
	(*TEETReady)(nil),                              // 12: teeproto.TEETReady
	(*RedactedRequest)(nil),                        // 13: teeproto.RedactedRequest
	(*RedactionVerification)(nil),                  // 14: teeproto.RedactionVerification
	(*RedactionStreams)(nil),                       // 15: teeproto.RedactionStreams
	(*ResponseRedactionSpec)(nil),                  // 16: teeproto.ResponseRedactionSpec
	(*EncryptedRequest)(nil),                       // 17: teeproto.EncryptedRequest
	(*EncryptedResponseData)(nil),                  // 18: teeproto.EncryptedResponseData
	(*ResponseTagVerification)(nil),                // 19: teeproto.ResponseTagVerification
	(*BatchedEncryptedResponses)(nil),              // 20: teeproto.BatchedEncryptedResponses
	(*BatchedResponseLengths)(nil),                 // 21: teeproto.BatchedResponseLengths
	(*BatchedTagSecrets)(nil),                      // 22: teeproto.BatchedTagSecrets
	(*BatchedTagVerifications)(nil),                // 23: teeproto.BatchedTagVerifications
	(*BatchedDecryptionStreams)(nil),               // 24: teeproto.BatchedDecryptionStreams
	(*BatchedSignedRedactedDecryptionStreams)(nil), // 25: teeproto.BatchedSignedRedactedDecryptionStreams
	(*AttestationResponse)(nil),                    // 26: teeproto.AttestationResponse
	(*SessionCreated)(nil),                         // 27: teeproto.SessionCreated
	(*SessionReady)(nil),                           // 28: teeproto.SessionReady
	(*BatchedResponseLengths_Length)(nil),          // 29: teeproto.BatchedResponseLengths.Length
	(*BatchedTagSecrets_TagSecret)(nil),            // 30: teeproto.BatchedTagSecrets.TagSecret
	(*BatchedTagVerifications_Verification)(nil),   // 31: teeproto.BatchedTagVerifications.Verification
	(*ErrorData)(nil),                              // 32: teeproto.ErrorData
	(*FinishedMessage)(nil),                        // 33: teeproto.FinishedMessage
	(*AttestationRequestData)(nil),                 // 34: teeproto.AttestationRequestData
	(*SignedMessage)(nil),                          // 35: teeproto.SignedMessage
	(*RequestRedactionRange)(nil),                  // 36: teeproto.RequestRedactionRange
	(*ResponseRedactionRange)(nil),                 // 37: teeproto.ResponseRedactionRange
	(*ResponseDecryptionStreamData)(nil),           // 38: teeproto.ResponseDecryptionStreamData
	(*SignedRedactedDecryptionStream)(nil),         // 39: teeproto.SignedRedactedDecryptionStream
	(*AttestationReport)(nil),                      // 40: teeproto.AttestationReport
}
var file_transport_proto_depIdxs = []int32{
	0,  // 0: teeproto.Envelope.sender:type_name -> teeproto.Sender
	3,  // 1: teeproto.Envelope.connection_ready:type_name -> teeproto.ConnectionReady
	4,  // 2: teeproto.Envelope.tcp_ready:type_name -> teeproto.TCPReady
	32, // 3: teeproto.Envelope.error:type_name -> teeproto.ErrorData
	33, // 4: teeproto.Envelope.finished:type_name -> teeproto.FinishedMessage
	27, // 5: teeproto.Envelope.session_created:type_name -> teeproto.SessionCreated
	28, // 6: teeproto.Envelope.session_ready:type_name -> teeproto.SessionReady
	2,  // 7: teeproto.Envelope.request_connection:type_name -> teeproto.RequestConnection
	5,  // 8: teeproto.Envelope.tcp_data:type_name -> teeproto.TCPData
	6,  // 9: teeproto.Envelope.handshake_complete:type_name -> teeproto.HandshakeComplete
	7,  // 10: teeproto.Envelope.handshake_key_disclosure:type_name -> teeproto.HandshakeKeyDisclosure
	8,  // 11: teeproto.Envelope.http_response:type_name -> teeproto.HTTPResponse
	9,  // 12: teeproto.Envelope.key_share_request:type_name -> teeproto.KeyShareRequest
	17, // 13: teeproto.Envelope.encrypted_request:type_name -> teeproto.EncryptedRequest
	10, // 14: teeproto.Envelope.key_share_response:type_name -> teeproto.KeyShareResponse
	13, // 15: teeproto.Envelope.redacted_request:type_name -> teeproto.RedactedRequest
	15, // 16: teeproto.Envelope.redaction_streams:type_name -> teeproto.RedactionStreams
	14, // 17: teeproto.Envelope.redaction_verification:type_name -> teeproto.RedactionVerification
	16, // 18: teeproto.Envelope.response_redaction_spec:type_name -> teeproto.ResponseRedactionSpec
	11, // 19: teeproto.Envelope.encrypted_data:type_name -> teeproto.EncryptedDataResponse
	18, // 20: teeproto.Envelope.encrypted_response:type_name -> teeproto.EncryptedResponseData
	20, // 21: teeproto.Envelope.batched_encrypted_responses:type_name -> teeproto.BatchedEncryptedResponses
	21, // 22: teeproto.Envelope.batched_response_lengths:type_name -> teeproto.BatchedResponseLengths
	22, // 23: teeproto.Envelope.batched_tag_secrets:type_name -> teeproto.BatchedTagSecrets
	23, // 24: teeproto.Envelope.batched_tag_verifications:type_name -> teeproto.BatchedTagVerifications
	24, // 25: teeproto.Envelope.batched_decryption_streams:type_name -> teeproto.BatchedDecryptionStreams
	25, // 26: teeproto.Envelope.batched_signed_redacted_decryption_streams:type_name -> teeproto.BatchedSignedRedactedDecryptionStreams
	34, // 27: teeproto.Envelope.attestation_request:type_name -> teeproto.AttestationRequestData
	26, // 28: teeproto.Envelope.attestation_response:type_name -> teeproto.AttestationResponse
	12, // 29: teeproto.Envelope.teet_ready:type_name -> teeproto.TEETReady
	35, // 30: teeproto.Envelope.signed_message:type_name -> teeproto.SignedMessage
	36, // 31: teeproto.RedactedRequest.redaction_ranges:type_name -> teeproto.RequestRedactionRange
	37, // 32: teeproto.ResponseRedactionSpec.ranges:type_name -> teeproto.ResponseRedactionRange
	36, // 33: teeproto.EncryptedRequest.redaction_ranges:type_name -> teeproto.RequestRedactionRange
	18, // 34: teeproto.BatchedEncryptedResponses.responses:type_name -> teeproto.EncryptedResponseData
	29, // 35: teeproto.BatchedResponseLengths.lengths:type_name -> teeproto.BatchedResponseLengths.Length
	30, // 36: teeproto.BatchedTagSecrets.tag_secrets:type_name -> teeproto.BatchedTagSecrets.TagSecret
	31, // 37: teeproto.BatchedTagVerifications.verifications:type_name -> teeproto.BatchedTagVerifications.Verification
	38, // 38: teeproto.BatchedDecryptionStreams.decryption_streams:type_name -> teeproto.ResponseDecryptionStreamData
	39, // 39: teeproto.BatchedSignedRedactedDecryptionStreams.signed_redacted_streams:type_name -> teeproto.SignedRedactedDecryptionStream
	40, // 40: teeproto.AttestationResponse.attestation_report:type_name -> teeproto.AttestationReport
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_transport_proto_init() }
func file_transport_proto_init() {
	if File_transport_proto != nil {
		return
	}
	file_common_proto_init()
	file_signing_proto_init()
	file_transport_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_ConnectionReady)(nil),
		(*Envelope_TcpReady)(nil),
		(*Envelope_Error)(nil),
		(*Envelope_Finished)(nil),
		(*Envelope_SessionCreated)(nil),
		(*Envelope_SessionReady)(nil),
		(*Envelope_RequestConnection)(nil),
		(*Envelope_TcpData)(nil),
		(*Envelope_HandshakeComplete)(nil),
		(*Envelope_HandshakeKeyDisclosure)(nil),
		(*Envelope_HttpResponse)(nil),
		(*Envelope_KeyShareRequest)(nil),
		(*Envelope_EncryptedRequest)(nil),
		(*Envelope_KeyShareResponse)(nil),
		(*Envelope_RedactedRequest)(nil),
		(*Envelope_RedactionStreams)(nil),
		(*Envelope_RedactionVerification)(nil),
		(*Envelope_ResponseRedactionSpec)(nil),
		(*Envelope_EncryptedData)(nil),
		(*Envelope_EncryptedResponse)(nil),
		(*Envelope_BatchedEncryptedResponses)(nil),
		(*Envelope_BatchedResponseLengths)(nil),
		(*Envelope_BatchedTagSecrets)(nil),
		(*Envelope_BatchedTagVerifications)(nil),
		(*Envelope_BatchedDecryptionStreams)(nil),
		(*Envelope_BatchedSignedRedactedDecryptionStreams)(nil),
		(*Envelope_AttestationRequest)(nil),
		(*Envelope_AttestationResponse)(nil),
		(*Envelope_TeetReady)(nil),
		(*Envelope_SignedMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_proto_goTypes,
		DependencyIndexes: file_transport_proto_depIdxs,
		EnumInfos:         file_transport_proto_enumTypes,
		MessageInfos:      file_transport_proto_msgTypes,
	}.Build()
	File_transport_proto = out.File
	file_transport_proto_goTypes = nil
	file_transport_proto_depIdxs = nil
}
